CREATE TABLE agent_run_telemetry (
  run_id TEXT PRIMARY KEY,
  workspace_id TEXT NOT NULL,
  task_id TEXT NOT NULL,
  profile_id TEXT,
  profile_name TEXT,
  harness TEXT NOT NULL,
  model TEXT NOT NULL DEFAULT 'unknown',
  invocation_class TEXT NOT NULL DEFAULT 'agent',
  status TEXT NOT NULL,
  input_tokens_known INTEGER NOT NULL DEFAULT 0,
  input_tokens INTEGER,
  output_tokens_known INTEGER NOT NULL DEFAULT 0,
  output_tokens INTEGER,
  estimated_cost_known INTEGER NOT NULL DEFAULT 0,
  estimated_cost_micros INTEGER,
  duration_ms_known INTEGER NOT NULL DEFAULT 0,
  duration_ms INTEGER,
  exit_code_known INTEGER NOT NULL DEFAULT 0,
  exit_code INTEGER,
  owned_by_ari INTEGER NOT NULL DEFAULT 1,
  pid_known INTEGER NOT NULL DEFAULT 0,
  pid INTEGER,
  cpu_time_ms_known INTEGER NOT NULL DEFAULT 0,
  cpu_time_ms INTEGER,
  memory_rss_bytes_peak_known INTEGER NOT NULL DEFAULT 0,
  memory_rss_bytes_peak INTEGER,
  child_processes_peak_known INTEGER NOT NULL DEFAULT 0,
  child_processes_peak INTEGER,
  ports_json TEXT NOT NULL DEFAULT '[]',
  orphan_state TEXT NOT NULL DEFAULT 'unknown',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  FOREIGN KEY(workspace_id) REFERENCES workspaces(workspace_id) ON DELETE CASCADE,
  FOREIGN KEY(profile_id) REFERENCES agent_profiles(profile_id) ON DELETE SET NULL
);

CREATE INDEX agent_run_telemetry_workspace_group_idx
ON agent_run_telemetry(workspace_id, profile_id, profile_name, harness, model, invocation_class);
