// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package world

import (
	"database/sql"
)

type Decision struct {
	ID           string         `json:"id"`
	Title        string         `json:"title"`
	Content      string         `json:"content"`
	Context      sql.NullString `json:"context"`
	Consequences sql.NullString `json:"consequences"`
	CreatedAt    string         `json:"created_at"`
	UpdatedAt    string         `json:"updated_at"`
}

type Knowledge struct {
	ID        string         `json:"id"`
	Type      string         `json:"type"`
	Name      string         `json:"name"`
	Content   sql.NullString `json:"content"`
	Metadata  sql.NullString `json:"metadata"`
	CreatedAt string         `json:"created_at"`
}

type KnowledgeRelation struct {
	FromID   string `json:"from_id"`
	ToID     string `json:"to_id"`
	Relation string `json:"relation"`
}

type Plan struct {
	ID        string `json:"id"`
	Title     string `json:"title"`
	Status    string `json:"status"`
	Content   string `json:"content"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type Project struct {
	ProjectID string `json:"project_id"`
	RootPath  string `json:"root_path"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type Session struct {
	SessionID string `json:"session_id"`
	ProjectID string `json:"project_id"`
	Status    string `json:"status"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}
