// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: world.sql

package world

import (
	"context"
	"database/sql"
)

const createDecision = `-- name: CreateDecision :execresult
INSERT INTO decisions (id, title, content, context, consequences, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateDecisionParams struct {
	ID           string         `json:"id"`
	Title        string         `json:"title"`
	Content      string         `json:"content"`
	Context      sql.NullString `json:"context"`
	Consequences sql.NullString `json:"consequences"`
	CreatedAt    string         `json:"created_at"`
	UpdatedAt    string         `json:"updated_at"`
}

func (q *Queries) CreateDecision(ctx context.Context, arg CreateDecisionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createDecision,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.Context,
		arg.Consequences,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const createKnowledge = `-- name: CreateKnowledge :execresult
INSERT INTO knowledge (id, type, name, content, metadata, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateKnowledgeParams struct {
	ID        string         `json:"id"`
	Type      string         `json:"type"`
	Name      string         `json:"name"`
	Content   sql.NullString `json:"content"`
	Metadata  sql.NullString `json:"metadata"`
	CreatedAt string         `json:"created_at"`
}

func (q *Queries) CreateKnowledge(ctx context.Context, arg CreateKnowledgeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createKnowledge,
		arg.ID,
		arg.Type,
		arg.Name,
		arg.Content,
		arg.Metadata,
		arg.CreatedAt,
	)
}

const createPlan = `-- name: CreatePlan :execresult
INSERT INTO plans (id, title, status, content, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreatePlanParams struct {
	ID        string `json:"id"`
	Title     string `json:"title"`
	Status    string `json:"status"`
	Content   string `json:"content"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

func (q *Queries) CreatePlan(ctx context.Context, arg CreatePlanParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPlan,
		arg.ID,
		arg.Title,
		arg.Status,
		arg.Content,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const createRelation = `-- name: CreateRelation :execresult
INSERT INTO knowledge_relations (from_id, to_id, relation)
VALUES (?, ?, ?)
`

type CreateRelationParams struct {
	FromID   string `json:"from_id"`
	ToID     string `json:"to_id"`
	Relation string `json:"relation"`
}

func (q *Queries) CreateRelation(ctx context.Context, arg CreateRelationParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createRelation, arg.FromID, arg.ToID, arg.Relation)
}

const deleteDecision = `-- name: DeleteDecision :exec
DELETE FROM decisions WHERE id = ?
`

func (q *Queries) DeleteDecision(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteDecision, id)
	return err
}

const deleteKnowledge = `-- name: DeleteKnowledge :exec
DELETE FROM knowledge WHERE id = ?
`

func (q *Queries) DeleteKnowledge(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteKnowledge, id)
	return err
}

const deletePlan = `-- name: DeletePlan :exec
DELETE FROM plans WHERE id = ?
`

func (q *Queries) DeletePlan(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deletePlan, id)
	return err
}

const deleteRelation = `-- name: DeleteRelation :exec
DELETE FROM knowledge_relations WHERE from_id = ? AND to_id = ? AND relation = ?
`

type DeleteRelationParams struct {
	FromID   string `json:"from_id"`
	ToID     string `json:"to_id"`
	Relation string `json:"relation"`
}

func (q *Queries) DeleteRelation(ctx context.Context, arg DeleteRelationParams) error {
	_, err := q.db.ExecContext(ctx, deleteRelation, arg.FromID, arg.ToID, arg.Relation)
	return err
}

const getDecision = `-- name: GetDecision :one
SELECT id, title, content, context, consequences, created_at, updated_at FROM decisions WHERE id = ? LIMIT 1
`

func (q *Queries) GetDecision(ctx context.Context, id string) (Decision, error) {
	row := q.db.QueryRowContext(ctx, getDecision, id)
	var i Decision
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Context,
		&i.Consequences,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getKnowledge = `-- name: GetKnowledge :one
SELECT id, type, name, content, metadata, created_at FROM knowledge WHERE id = ? LIMIT 1
`

func (q *Queries) GetKnowledge(ctx context.Context, id string) (Knowledge, error) {
	row := q.db.QueryRowContext(ctx, getKnowledge, id)
	var i Knowledge
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.Content,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getPlan = `-- name: GetPlan :one
SELECT id, title, status, content, created_at, updated_at FROM plans WHERE id = ? LIMIT 1
`

func (q *Queries) GetPlan(ctx context.Context, id string) (Plan, error) {
	row := q.db.QueryRowContext(ctx, getPlan, id)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRelationsFrom = `-- name: GetRelationsFrom :many
SELECT from_id, to_id, relation FROM knowledge_relations WHERE from_id = ?
`

func (q *Queries) GetRelationsFrom(ctx context.Context, fromID string) ([]KnowledgeRelation, error) {
	rows, err := q.db.QueryContext(ctx, getRelationsFrom, fromID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KnowledgeRelation{}
	for rows.Next() {
		var i KnowledgeRelation
		if err := rows.Scan(&i.FromID, &i.ToID, &i.Relation); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRelationsTo = `-- name: GetRelationsTo :many
SELECT from_id, to_id, relation FROM knowledge_relations WHERE to_id = ?
`

func (q *Queries) GetRelationsTo(ctx context.Context, toID string) ([]KnowledgeRelation, error) {
	rows, err := q.db.QueryContext(ctx, getRelationsTo, toID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KnowledgeRelation{}
	for rows.Next() {
		var i KnowledgeRelation
		if err := rows.Scan(&i.FromID, &i.ToID, &i.Relation); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDecisions = `-- name: ListDecisions :many
SELECT id, title, content, context, consequences, created_at, updated_at FROM decisions ORDER BY created_at DESC
`

func (q *Queries) ListDecisions(ctx context.Context) ([]Decision, error) {
	rows, err := q.db.QueryContext(ctx, listDecisions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Decision{}
	for rows.Next() {
		var i Decision
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.Context,
			&i.Consequences,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKnowledge = `-- name: ListKnowledge :many
SELECT id, type, name, content, metadata, created_at FROM knowledge ORDER BY created_at DESC
`

func (q *Queries) ListKnowledge(ctx context.Context) ([]Knowledge, error) {
	rows, err := q.db.QueryContext(ctx, listKnowledge)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Knowledge{}
	for rows.Next() {
		var i Knowledge
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.Content,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKnowledgeByType = `-- name: ListKnowledgeByType :many
SELECT id, type, name, content, metadata, created_at FROM knowledge WHERE type = ? ORDER BY created_at DESC
`

func (q *Queries) ListKnowledgeByType(ctx context.Context, type_ string) ([]Knowledge, error) {
	rows, err := q.db.QueryContext(ctx, listKnowledgeByType, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Knowledge{}
	for rows.Next() {
		var i Knowledge
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.Content,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlans = `-- name: ListPlans :many
SELECT id, title, status, content, created_at, updated_at FROM plans ORDER BY created_at DESC
`

func (q *Queries) ListPlans(ctx context.Context) ([]Plan, error) {
	rows, err := q.db.QueryContext(ctx, listPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Plan{}
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Status,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlansByStatus = `-- name: ListPlansByStatus :many
SELECT id, title, status, content, created_at, updated_at FROM plans WHERE status = ? ORDER BY created_at DESC
`

func (q *Queries) ListPlansByStatus(ctx context.Context, status string) ([]Plan, error) {
	rows, err := q.db.QueryContext(ctx, listPlansByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Plan{}
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Status,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDecision = `-- name: UpdateDecision :execresult
UPDATE decisions
SET title = ?, content = ?, context = ?, consequences = ?, updated_at = ?
WHERE id = ?
`

type UpdateDecisionParams struct {
	Title        string         `json:"title"`
	Content      string         `json:"content"`
	Context      sql.NullString `json:"context"`
	Consequences sql.NullString `json:"consequences"`
	UpdatedAt    string         `json:"updated_at"`
	ID           string         `json:"id"`
}

func (q *Queries) UpdateDecision(ctx context.Context, arg UpdateDecisionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateDecision,
		arg.Title,
		arg.Content,
		arg.Context,
		arg.Consequences,
		arg.UpdatedAt,
		arg.ID,
	)
}

const updateKnowledge = `-- name: UpdateKnowledge :execresult
UPDATE knowledge
SET type = ?, name = ?, content = ?, metadata = ?
WHERE id = ?
`

type UpdateKnowledgeParams struct {
	Type     string         `json:"type"`
	Name     string         `json:"name"`
	Content  sql.NullString `json:"content"`
	Metadata sql.NullString `json:"metadata"`
	ID       string         `json:"id"`
}

func (q *Queries) UpdateKnowledge(ctx context.Context, arg UpdateKnowledgeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateKnowledge,
		arg.Type,
		arg.Name,
		arg.Content,
		arg.Metadata,
		arg.ID,
	)
}

const updatePlan = `-- name: UpdatePlan :execresult
UPDATE plans
SET title = ?, status = ?, content = ?, updated_at = ?
WHERE id = ?
`

type UpdatePlanParams struct {
	Title     string `json:"title"`
	Status    string `json:"status"`
	Content   string `json:"content"`
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdatePlan(ctx context.Context, arg UpdatePlanParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updatePlan,
		arg.Title,
		arg.Status,
		arg.Content,
		arg.UpdatedAt,
		arg.ID,
	)
}
