// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: agent_profiles.sql

package dbsqlc

import (
	"context"
)

const getGlobalProfileByName = `-- name: GetGlobalProfileByName :one
SELECT
  profile_id,
  workspace_id,
  name,
  harness,
  model,
  prompt,
  auth_slot_id,
  auth_pool_json,
  invocation_class,
  defaults_json,
  created_at,
  updated_at
FROM agent_profiles
WHERE workspace_id IS NULL AND name = ?
LIMIT 1
`

type GetGlobalProfileByNameParams struct {
	Name string `json:"name"`
}

type GetGlobalProfileByNameRow struct {
	ProfileID       string  `json:"profile_id"`
	WorkspaceID     *string `json:"workspace_id"`
	Name            string  `json:"name"`
	Harness         *string `json:"harness"`
	Model           *string `json:"model"`
	Prompt          *string `json:"prompt"`
	AuthSlotID      *string `json:"auth_slot_id"`
	AuthPoolJson    string  `json:"auth_pool_json"`
	InvocationClass *string `json:"invocation_class"`
	DefaultsJson    string  `json:"defaults_json"`
	CreatedAt       string  `json:"created_at"`
	UpdatedAt       string  `json:"updated_at"`
}

func (q *Queries) GetGlobalProfileByName(ctx context.Context, arg GetGlobalProfileByNameParams) (GetGlobalProfileByNameRow, error) {
	row := q.db.QueryRowContext(ctx, getGlobalProfileByName, arg.Name)
	var i GetGlobalProfileByNameRow
	err := row.Scan(
		&i.ProfileID,
		&i.WorkspaceID,
		&i.Name,
		&i.Harness,
		&i.Model,
		&i.Prompt,
		&i.AuthSlotID,
		&i.AuthPoolJson,
		&i.InvocationClass,
		&i.DefaultsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceProfileByName = `-- name: GetWorkspaceProfileByName :one
SELECT
  profile_id,
  workspace_id,
  name,
  harness,
  model,
  prompt,
  auth_slot_id,
  auth_pool_json,
  invocation_class,
  defaults_json,
  created_at,
  updated_at
FROM agent_profiles
WHERE workspace_id = ? AND name = ?
LIMIT 1
`

type GetWorkspaceProfileByNameParams struct {
	WorkspaceID *string `json:"workspace_id"`
	Name        string  `json:"name"`
}

type GetWorkspaceProfileByNameRow struct {
	ProfileID       string  `json:"profile_id"`
	WorkspaceID     *string `json:"workspace_id"`
	Name            string  `json:"name"`
	Harness         *string `json:"harness"`
	Model           *string `json:"model"`
	Prompt          *string `json:"prompt"`
	AuthSlotID      *string `json:"auth_slot_id"`
	AuthPoolJson    string  `json:"auth_pool_json"`
	InvocationClass *string `json:"invocation_class"`
	DefaultsJson    string  `json:"defaults_json"`
	CreatedAt       string  `json:"created_at"`
	UpdatedAt       string  `json:"updated_at"`
}

func (q *Queries) GetWorkspaceProfileByName(ctx context.Context, arg GetWorkspaceProfileByNameParams) (GetWorkspaceProfileByNameRow, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceProfileByName, arg.WorkspaceID, arg.Name)
	var i GetWorkspaceProfileByNameRow
	err := row.Scan(
		&i.ProfileID,
		&i.WorkspaceID,
		&i.Name,
		&i.Harness,
		&i.Model,
		&i.Prompt,
		&i.AuthSlotID,
		&i.AuthPoolJson,
		&i.InvocationClass,
		&i.DefaultsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGlobalProfiles = `-- name: ListGlobalProfiles :many
SELECT
  profile_id,
  workspace_id,
  name,
  harness,
  model,
  prompt,
  auth_slot_id,
  auth_pool_json,
  invocation_class,
  defaults_json,
  created_at,
  updated_at
FROM agent_profiles
WHERE workspace_id IS NULL
ORDER BY name ASC, profile_id ASC
`

type ListGlobalProfilesRow struct {
	ProfileID       string  `json:"profile_id"`
	WorkspaceID     *string `json:"workspace_id"`
	Name            string  `json:"name"`
	Harness         *string `json:"harness"`
	Model           *string `json:"model"`
	Prompt          *string `json:"prompt"`
	AuthSlotID      *string `json:"auth_slot_id"`
	AuthPoolJson    string  `json:"auth_pool_json"`
	InvocationClass *string `json:"invocation_class"`
	DefaultsJson    string  `json:"defaults_json"`
	CreatedAt       string  `json:"created_at"`
	UpdatedAt       string  `json:"updated_at"`
}

func (q *Queries) ListGlobalProfiles(ctx context.Context) ([]ListGlobalProfilesRow, error) {
	rows, err := q.db.QueryContext(ctx, listGlobalProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGlobalProfilesRow{}
	for rows.Next() {
		var i ListGlobalProfilesRow
		if err := rows.Scan(
			&i.ProfileID,
			&i.WorkspaceID,
			&i.Name,
			&i.Harness,
			&i.Model,
			&i.Prompt,
			&i.AuthSlotID,
			&i.AuthPoolJson,
			&i.InvocationClass,
			&i.DefaultsJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceProfiles = `-- name: ListWorkspaceProfiles :many
SELECT
  profile_id,
  workspace_id,
  name,
  harness,
  model,
  prompt,
  auth_slot_id,
  auth_pool_json,
  invocation_class,
  defaults_json,
  created_at,
  updated_at
FROM agent_profiles
WHERE workspace_id = ?
ORDER BY name ASC, profile_id ASC
`

type ListWorkspaceProfilesParams struct {
	WorkspaceID *string `json:"workspace_id"`
}

type ListWorkspaceProfilesRow struct {
	ProfileID       string  `json:"profile_id"`
	WorkspaceID     *string `json:"workspace_id"`
	Name            string  `json:"name"`
	Harness         *string `json:"harness"`
	Model           *string `json:"model"`
	Prompt          *string `json:"prompt"`
	AuthSlotID      *string `json:"auth_slot_id"`
	AuthPoolJson    string  `json:"auth_pool_json"`
	InvocationClass *string `json:"invocation_class"`
	DefaultsJson    string  `json:"defaults_json"`
	CreatedAt       string  `json:"created_at"`
	UpdatedAt       string  `json:"updated_at"`
}

func (q *Queries) ListWorkspaceProfiles(ctx context.Context, arg ListWorkspaceProfilesParams) ([]ListWorkspaceProfilesRow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaceProfiles, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceProfilesRow{}
	for rows.Next() {
		var i ListWorkspaceProfilesRow
		if err := rows.Scan(
			&i.ProfileID,
			&i.WorkspaceID,
			&i.Name,
			&i.Harness,
			&i.Model,
			&i.Prompt,
			&i.AuthSlotID,
			&i.AuthPoolJson,
			&i.InvocationClass,
			&i.DefaultsJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProfile = `-- name: UpsertProfile :exec
INSERT INTO agent_profiles (
  profile_id,
  workspace_id,
  name,
  harness,
  model,
  prompt,
  auth_slot_id,
  auth_pool_json,
  invocation_class,
  defaults_json,
  created_at,
  updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(profile_id) DO UPDATE SET
  workspace_id = excluded.workspace_id,
  name = excluded.name,
  harness = excluded.harness,
  model = excluded.model,
  prompt = excluded.prompt,
  auth_slot_id = excluded.auth_slot_id,
  auth_pool_json = excluded.auth_pool_json,
  invocation_class = excluded.invocation_class,
  defaults_json = excluded.defaults_json,
  updated_at = excluded.updated_at
`

type UpsertProfileParams struct {
	ProfileID       string  `json:"profile_id"`
	WorkspaceID     *string `json:"workspace_id"`
	Name            string  `json:"name"`
	Harness         *string `json:"harness"`
	Model           *string `json:"model"`
	Prompt          *string `json:"prompt"`
	AuthSlotID      *string `json:"auth_slot_id"`
	AuthPoolJson    string  `json:"auth_pool_json"`
	InvocationClass *string `json:"invocation_class"`
	DefaultsJson    string  `json:"defaults_json"`
	CreatedAt       string  `json:"created_at"`
	UpdatedAt       string  `json:"updated_at"`
}

func (q *Queries) UpsertProfile(ctx context.Context, arg UpsertProfileParams) error {
	_, err := q.db.ExecContext(ctx, upsertProfile,
		arg.ProfileID,
		arg.WorkspaceID,
		arg.Name,
		arg.Harness,
		arg.Model,
		arg.Prompt,
		arg.AuthSlotID,
		arg.AuthPoolJson,
		arg.InvocationClass,
		arg.DefaultsJson,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
