// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: agent_profiles.sql

package dbsqlc

import (
	"context"
)

const getGlobalAgentProfileByName = `-- name: GetGlobalAgentProfileByName :one
SELECT
  profile_id,
  workspace_id,
  name,
  harness,
  model,
  prompt,
  auth_slot_id,
  auth_pool_json,
  invocation_class,
  defaults_json,
  created_at,
  updated_at
FROM agent_profiles
WHERE workspace_id IS NULL AND name = ?
LIMIT 1
`

type GetGlobalAgentProfileByNameParams struct {
	Name string `json:"name"`
}

type GetGlobalAgentProfileByNameRow struct {
	ProfileID       string  `json:"profile_id"`
	WorkspaceID     *string `json:"workspace_id"`
	Name            string  `json:"name"`
	Harness         *string `json:"harness"`
	Model           *string `json:"model"`
	Prompt          *string `json:"prompt"`
	AuthSlotID      *string `json:"auth_slot_id"`
	AuthPoolJson    string  `json:"auth_pool_json"`
	InvocationClass *string `json:"invocation_class"`
	DefaultsJson    string  `json:"defaults_json"`
	CreatedAt       string  `json:"created_at"`
	UpdatedAt       string  `json:"updated_at"`
}

func (q *Queries) GetGlobalAgentProfileByName(ctx context.Context, arg GetGlobalAgentProfileByNameParams) (GetGlobalAgentProfileByNameRow, error) {
	row := q.db.QueryRowContext(ctx, getGlobalAgentProfileByName, arg.Name)
	var i GetGlobalAgentProfileByNameRow
	err := row.Scan(
		&i.ProfileID,
		&i.WorkspaceID,
		&i.Name,
		&i.Harness,
		&i.Model,
		&i.Prompt,
		&i.AuthSlotID,
		&i.AuthPoolJson,
		&i.InvocationClass,
		&i.DefaultsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceAgentProfileByName = `-- name: GetWorkspaceAgentProfileByName :one
SELECT
  profile_id,
  workspace_id,
  name,
  harness,
  model,
  prompt,
  auth_slot_id,
  auth_pool_json,
  invocation_class,
  defaults_json,
  created_at,
  updated_at
FROM agent_profiles
WHERE workspace_id = ? AND name = ?
LIMIT 1
`

type GetWorkspaceAgentProfileByNameParams struct {
	WorkspaceID *string `json:"workspace_id"`
	Name        string  `json:"name"`
}

type GetWorkspaceAgentProfileByNameRow struct {
	ProfileID       string  `json:"profile_id"`
	WorkspaceID     *string `json:"workspace_id"`
	Name            string  `json:"name"`
	Harness         *string `json:"harness"`
	Model           *string `json:"model"`
	Prompt          *string `json:"prompt"`
	AuthSlotID      *string `json:"auth_slot_id"`
	AuthPoolJson    string  `json:"auth_pool_json"`
	InvocationClass *string `json:"invocation_class"`
	DefaultsJson    string  `json:"defaults_json"`
	CreatedAt       string  `json:"created_at"`
	UpdatedAt       string  `json:"updated_at"`
}

func (q *Queries) GetWorkspaceAgentProfileByName(ctx context.Context, arg GetWorkspaceAgentProfileByNameParams) (GetWorkspaceAgentProfileByNameRow, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceAgentProfileByName, arg.WorkspaceID, arg.Name)
	var i GetWorkspaceAgentProfileByNameRow
	err := row.Scan(
		&i.ProfileID,
		&i.WorkspaceID,
		&i.Name,
		&i.Harness,
		&i.Model,
		&i.Prompt,
		&i.AuthSlotID,
		&i.AuthPoolJson,
		&i.InvocationClass,
		&i.DefaultsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGlobalAgentProfiles = `-- name: ListGlobalAgentProfiles :many
SELECT
  profile_id,
  workspace_id,
  name,
  harness,
  model,
  prompt,
  auth_slot_id,
  auth_pool_json,
  invocation_class,
  defaults_json,
  created_at,
  updated_at
FROM agent_profiles
WHERE workspace_id IS NULL
ORDER BY name ASC, profile_id ASC
`

type ListGlobalAgentProfilesRow struct {
	ProfileID       string  `json:"profile_id"`
	WorkspaceID     *string `json:"workspace_id"`
	Name            string  `json:"name"`
	Harness         *string `json:"harness"`
	Model           *string `json:"model"`
	Prompt          *string `json:"prompt"`
	AuthSlotID      *string `json:"auth_slot_id"`
	AuthPoolJson    string  `json:"auth_pool_json"`
	InvocationClass *string `json:"invocation_class"`
	DefaultsJson    string  `json:"defaults_json"`
	CreatedAt       string  `json:"created_at"`
	UpdatedAt       string  `json:"updated_at"`
}

func (q *Queries) ListGlobalAgentProfiles(ctx context.Context) ([]ListGlobalAgentProfilesRow, error) {
	rows, err := q.db.QueryContext(ctx, listGlobalAgentProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGlobalAgentProfilesRow{}
	for rows.Next() {
		var i ListGlobalAgentProfilesRow
		if err := rows.Scan(
			&i.ProfileID,
			&i.WorkspaceID,
			&i.Name,
			&i.Harness,
			&i.Model,
			&i.Prompt,
			&i.AuthSlotID,
			&i.AuthPoolJson,
			&i.InvocationClass,
			&i.DefaultsJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceAgentProfiles = `-- name: ListWorkspaceAgentProfiles :many
SELECT
  profile_id,
  workspace_id,
  name,
  harness,
  model,
  prompt,
  auth_slot_id,
  auth_pool_json,
  invocation_class,
  defaults_json,
  created_at,
  updated_at
FROM agent_profiles
WHERE workspace_id = ?
ORDER BY name ASC, profile_id ASC
`

type ListWorkspaceAgentProfilesParams struct {
	WorkspaceID *string `json:"workspace_id"`
}

type ListWorkspaceAgentProfilesRow struct {
	ProfileID       string  `json:"profile_id"`
	WorkspaceID     *string `json:"workspace_id"`
	Name            string  `json:"name"`
	Harness         *string `json:"harness"`
	Model           *string `json:"model"`
	Prompt          *string `json:"prompt"`
	AuthSlotID      *string `json:"auth_slot_id"`
	AuthPoolJson    string  `json:"auth_pool_json"`
	InvocationClass *string `json:"invocation_class"`
	DefaultsJson    string  `json:"defaults_json"`
	CreatedAt       string  `json:"created_at"`
	UpdatedAt       string  `json:"updated_at"`
}

func (q *Queries) ListWorkspaceAgentProfiles(ctx context.Context, arg ListWorkspaceAgentProfilesParams) ([]ListWorkspaceAgentProfilesRow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaceAgentProfiles, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceAgentProfilesRow{}
	for rows.Next() {
		var i ListWorkspaceAgentProfilesRow
		if err := rows.Scan(
			&i.ProfileID,
			&i.WorkspaceID,
			&i.Name,
			&i.Harness,
			&i.Model,
			&i.Prompt,
			&i.AuthSlotID,
			&i.AuthPoolJson,
			&i.InvocationClass,
			&i.DefaultsJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAgentProfile = `-- name: UpsertAgentProfile :exec
INSERT INTO agent_profiles (
  profile_id,
  workspace_id,
  name,
  harness,
  model,
  prompt,
  auth_slot_id,
  auth_pool_json,
  invocation_class,
  defaults_json,
  created_at,
  updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(profile_id) DO UPDATE SET
  workspace_id = excluded.workspace_id,
  name = excluded.name,
  harness = excluded.harness,
  model = excluded.model,
  prompt = excluded.prompt,
  auth_slot_id = excluded.auth_slot_id,
  auth_pool_json = excluded.auth_pool_json,
  invocation_class = excluded.invocation_class,
  defaults_json = excluded.defaults_json,
  updated_at = excluded.updated_at
`

type UpsertAgentProfileParams struct {
	ProfileID       string  `json:"profile_id"`
	WorkspaceID     *string `json:"workspace_id"`
	Name            string  `json:"name"`
	Harness         *string `json:"harness"`
	Model           *string `json:"model"`
	Prompt          *string `json:"prompt"`
	AuthSlotID      *string `json:"auth_slot_id"`
	AuthPoolJson    string  `json:"auth_pool_json"`
	InvocationClass *string `json:"invocation_class"`
	DefaultsJson    string  `json:"defaults_json"`
	CreatedAt       string  `json:"created_at"`
	UpdatedAt       string  `json:"updated_at"`
}

func (q *Queries) UpsertAgentProfile(ctx context.Context, arg UpsertAgentProfileParams) error {
	_, err := q.db.ExecContext(ctx, upsertAgentProfile,
		arg.ProfileID,
		arg.WorkspaceID,
		arg.Name,
		arg.Harness,
		arg.Model,
		arg.Prompt,
		arg.AuthSlotID,
		arg.AuthPoolJson,
		arg.InvocationClass,
		arg.DefaultsJson,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
