// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: agent_run_telemetry.sql

package dbsqlc

import (
	"context"
	"database/sql"
)

const listAgentRunTelemetryByWorkspace = `-- name: ListAgentRunTelemetryByWorkspace :many
SELECT run_id, workspace_id, task_id, profile_id, profile_name, harness, model, invocation_class, status, input_tokens_known, input_tokens, output_tokens_known, output_tokens, estimated_cost_known, estimated_cost_micros, duration_ms_known, duration_ms, exit_code_known, exit_code, owned_by_ari, pid_known, pid, cpu_time_ms_known, cpu_time_ms, memory_rss_bytes_peak_known, memory_rss_bytes_peak, child_processes_peak_known, child_processes_peak, ports_json, orphan_state, created_at, updated_at FROM agent_run_telemetry
WHERE workspace_id = ?
ORDER BY created_at DESC, run_id ASC
`

func (q *Queries) ListAgentRunTelemetryByWorkspace(ctx context.Context, workspaceID string) ([]AgentRunTelemetry, error) {
	rows, err := q.db.QueryContext(ctx, listAgentRunTelemetryByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentRunTelemetry{}
	for rows.Next() {
		var i AgentRunTelemetry
		if err := rows.Scan(
			&i.RunID,
			&i.WorkspaceID,
			&i.TaskID,
			&i.ProfileID,
			&i.ProfileName,
			&i.Harness,
			&i.Model,
			&i.InvocationClass,
			&i.Status,
			&i.InputTokensKnown,
			&i.InputTokens,
			&i.OutputTokensKnown,
			&i.OutputTokens,
			&i.EstimatedCostKnown,
			&i.EstimatedCostMicros,
			&i.DurationMsKnown,
			&i.DurationMs,
			&i.ExitCodeKnown,
			&i.ExitCode,
			&i.OwnedByAri,
			&i.PidKnown,
			&i.Pid,
			&i.CpuTimeMsKnown,
			&i.CpuTimeMs,
			&i.MemoryRssBytesPeakKnown,
			&i.MemoryRssBytesPeak,
			&i.ChildProcessesPeakKnown,
			&i.ChildProcessesPeak,
			&i.PortsJson,
			&i.OrphanState,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAgentRunTelemetry = `-- name: UpsertAgentRunTelemetry :exec
INSERT INTO agent_run_telemetry (
  run_id, workspace_id, task_id, profile_id, profile_name, harness, model, invocation_class, status,
  input_tokens_known, input_tokens, output_tokens_known, output_tokens,
  estimated_cost_known, estimated_cost_micros, duration_ms_known, duration_ms,
  exit_code_known, exit_code, owned_by_ari, pid_known, pid,
  cpu_time_ms_known, cpu_time_ms, memory_rss_bytes_peak_known, memory_rss_bytes_peak,
  child_processes_peak_known, child_processes_peak, ports_json, orphan_state, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(run_id) DO UPDATE SET
  status = excluded.status,
  input_tokens_known = excluded.input_tokens_known,
  input_tokens = excluded.input_tokens,
  output_tokens_known = excluded.output_tokens_known,
  output_tokens = excluded.output_tokens,
  estimated_cost_known = excluded.estimated_cost_known,
  estimated_cost_micros = excluded.estimated_cost_micros,
  duration_ms_known = excluded.duration_ms_known,
  duration_ms = excluded.duration_ms,
  exit_code_known = excluded.exit_code_known,
  exit_code = excluded.exit_code,
  owned_by_ari = excluded.owned_by_ari,
  pid_known = excluded.pid_known,
  pid = excluded.pid,
  cpu_time_ms_known = excluded.cpu_time_ms_known,
  cpu_time_ms = excluded.cpu_time_ms,
  memory_rss_bytes_peak_known = excluded.memory_rss_bytes_peak_known,
  memory_rss_bytes_peak = excluded.memory_rss_bytes_peak,
  child_processes_peak_known = excluded.child_processes_peak_known,
  child_processes_peak = excluded.child_processes_peak,
  ports_json = excluded.ports_json,
  orphan_state = excluded.orphan_state,
  updated_at = excluded.updated_at
`

type UpsertAgentRunTelemetryParams struct {
	RunID                   string         `json:"run_id"`
	WorkspaceID             string         `json:"workspace_id"`
	TaskID                  string         `json:"task_id"`
	ProfileID               sql.NullString `json:"profile_id"`
	ProfileName             sql.NullString `json:"profile_name"`
	Harness                 string         `json:"harness"`
	Model                   string         `json:"model"`
	InvocationClass         string         `json:"invocation_class"`
	Status                  string         `json:"status"`
	InputTokensKnown        int64          `json:"input_tokens_known"`
	InputTokens             sql.NullInt64  `json:"input_tokens"`
	OutputTokensKnown       int64          `json:"output_tokens_known"`
	OutputTokens            sql.NullInt64  `json:"output_tokens"`
	EstimatedCostKnown      int64          `json:"estimated_cost_known"`
	EstimatedCostMicros     sql.NullInt64  `json:"estimated_cost_micros"`
	DurationMsKnown         int64          `json:"duration_ms_known"`
	DurationMs              sql.NullInt64  `json:"duration_ms"`
	ExitCodeKnown           int64          `json:"exit_code_known"`
	ExitCode                sql.NullInt64  `json:"exit_code"`
	OwnedByAri              int64          `json:"owned_by_ari"`
	PidKnown                int64          `json:"pid_known"`
	Pid                     sql.NullInt64  `json:"pid"`
	CpuTimeMsKnown          int64          `json:"cpu_time_ms_known"`
	CpuTimeMs               sql.NullInt64  `json:"cpu_time_ms"`
	MemoryRssBytesPeakKnown int64          `json:"memory_rss_bytes_peak_known"`
	MemoryRssBytesPeak      sql.NullInt64  `json:"memory_rss_bytes_peak"`
	ChildProcessesPeakKnown int64          `json:"child_processes_peak_known"`
	ChildProcessesPeak      sql.NullInt64  `json:"child_processes_peak"`
	PortsJson               string         `json:"ports_json"`
	OrphanState             string         `json:"orphan_state"`
	CreatedAt               string         `json:"created_at"`
	UpdatedAt               string         `json:"updated_at"`
}

func (q *Queries) UpsertAgentRunTelemetry(ctx context.Context, arg UpsertAgentRunTelemetryParams) error {
	_, err := q.db.ExecContext(ctx, upsertAgentRunTelemetry,
		arg.RunID,
		arg.WorkspaceID,
		arg.TaskID,
		arg.ProfileID,
		arg.ProfileName,
		arg.Harness,
		arg.Model,
		arg.InvocationClass,
		arg.Status,
		arg.InputTokensKnown,
		arg.InputTokens,
		arg.OutputTokensKnown,
		arg.OutputTokens,
		arg.EstimatedCostKnown,
		arg.EstimatedCostMicros,
		arg.DurationMsKnown,
		arg.DurationMs,
		arg.ExitCodeKnown,
		arg.ExitCode,
		arg.OwnedByAri,
		arg.PidKnown,
		arg.Pid,
		arg.CpuTimeMsKnown,
		arg.CpuTimeMs,
		arg.MemoryRssBytesPeakKnown,
		arg.MemoryRssBytesPeak,
		arg.ChildProcessesPeakKnown,
		arg.ChildProcessesPeak,
		arg.PortsJson,
		arg.OrphanState,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
