// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: agents.sql

package dbsqlc

import (
	"context"
)

const createAgent = `-- name: CreateAgent :exec
INSERT INTO agents (
  agent_id, workspace_id, name, command, args, status, exit_code, started_at, stopped_at,
  harness, harness_resumable_id, harness_metadata, invocation_class
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateAgentParams struct {
	AgentID            string  `json:"agent_id"`
	WorkspaceID        string  `json:"workspace_id"`
	Name               *string `json:"name"`
	Command            string  `json:"command"`
	Args               string  `json:"args"`
	Status             string  `json:"status"`
	ExitCode           *int64  `json:"exit_code"`
	StartedAt          string  `json:"started_at"`
	StoppedAt          *string `json:"stopped_at"`
	Harness            *string `json:"harness"`
	HarnessResumableID *string `json:"harness_resumable_id"`
	HarnessMetadata    string  `json:"harness_metadata"`
	InvocationClass    string  `json:"invocation_class"`
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) error {
	_, err := q.db.ExecContext(ctx, createAgent,
		arg.AgentID,
		arg.WorkspaceID,
		arg.Name,
		arg.Command,
		arg.Args,
		arg.Status,
		arg.ExitCode,
		arg.StartedAt,
		arg.StoppedAt,
		arg.Harness,
		arg.HarnessResumableID,
		arg.HarnessMetadata,
		arg.InvocationClass,
	)
	return err
}

const getAgentByID = `-- name: GetAgentByID :one
SELECT agent_id, workspace_id, name, command, args, status, exit_code, started_at, stopped_at,
  harness, harness_resumable_id, harness_metadata, invocation_class
FROM agents
WHERE workspace_id = ? AND agent_id = ?
`

type GetAgentByIDParams struct {
	WorkspaceID string `json:"workspace_id"`
	AgentID     string `json:"agent_id"`
}

func (q *Queries) GetAgentByID(ctx context.Context, arg GetAgentByIDParams) (Agent, error) {
	row := q.db.QueryRowContext(ctx, getAgentByID, arg.WorkspaceID, arg.AgentID)
	var i Agent
	err := row.Scan(
		&i.AgentID,
		&i.WorkspaceID,
		&i.Name,
		&i.Command,
		&i.Args,
		&i.Status,
		&i.ExitCode,
		&i.StartedAt,
		&i.StoppedAt,
		&i.Harness,
		&i.HarnessResumableID,
		&i.HarnessMetadata,
		&i.InvocationClass,
	)
	return i, err
}

const getAgentByName = `-- name: GetAgentByName :one
SELECT agent_id, workspace_id, name, command, args, status, exit_code, started_at, stopped_at,
  harness, harness_resumable_id, harness_metadata, invocation_class
FROM agents
WHERE workspace_id = ? AND name = ?
`

type GetAgentByNameParams struct {
	WorkspaceID string  `json:"workspace_id"`
	Name        *string `json:"name"`
}

func (q *Queries) GetAgentByName(ctx context.Context, arg GetAgentByNameParams) (Agent, error) {
	row := q.db.QueryRowContext(ctx, getAgentByName, arg.WorkspaceID, arg.Name)
	var i Agent
	err := row.Scan(
		&i.AgentID,
		&i.WorkspaceID,
		&i.Name,
		&i.Command,
		&i.Args,
		&i.Status,
		&i.ExitCode,
		&i.StartedAt,
		&i.StoppedAt,
		&i.Harness,
		&i.HarnessResumableID,
		&i.HarnessMetadata,
		&i.InvocationClass,
	)
	return i, err
}

const listAgentsByWorkspace = `-- name: ListAgentsByWorkspace :many
SELECT agent_id, workspace_id, name, command, args, status, exit_code, started_at, stopped_at,
  harness, harness_resumable_id, harness_metadata, invocation_class
FROM agents
WHERE workspace_id = ?
ORDER BY started_at DESC, agent_id ASC
`

type ListAgentsByWorkspaceParams struct {
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) ListAgentsByWorkspace(ctx context.Context, arg ListAgentsByWorkspaceParams) ([]Agent, error) {
	rows, err := q.db.QueryContext(ctx, listAgentsByWorkspace, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.AgentID,
			&i.WorkspaceID,
			&i.Name,
			&i.Command,
			&i.Args,
			&i.Status,
			&i.ExitCode,
			&i.StartedAt,
			&i.StoppedAt,
			&i.Harness,
			&i.HarnessResumableID,
			&i.HarnessMetadata,
			&i.InvocationClass,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRunningAgentsLost = `-- name: MarkRunningAgentsLost :exec
UPDATE agents
SET status = 'lost'
WHERE status = 'running'
`

func (q *Queries) MarkRunningAgentsLost(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, markRunningAgentsLost)
	return err
}

const updateAgentStatus = `-- name: UpdateAgentStatus :execrows
UPDATE agents
SET status = ?,
  exit_code = ?,
  stopped_at = ?
WHERE workspace_id = ? AND agent_id = ?
`

type UpdateAgentStatusParams struct {
	Status      string  `json:"status"`
	ExitCode    *int64  `json:"exit_code"`
	StoppedAt   *string `json:"stopped_at"`
	WorkspaceID string  `json:"workspace_id"`
	AgentID     string  `json:"agent_id"`
}

func (q *Queries) UpdateAgentStatus(ctx context.Context, arg UpdateAgentStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateAgentStatus,
		arg.Status,
		arg.ExitCode,
		arg.StoppedAt,
		arg.WorkspaceID,
		arg.AgentID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
