// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: agent_profiles.sql

package dbsqlc

import (
	"context"
	"database/sql"
)

const getGlobalAgentProfileByName = `-- name: GetGlobalAgentProfileByName :one
SELECT
  profile_id,
  workspace_id,
  name,
  harness,
  model,
  prompt,
  invocation_class,
  defaults_json,
  created_at,
  updated_at
FROM agent_profiles
WHERE workspace_id IS NULL AND name = ?
LIMIT 1
`

func (q *Queries) GetGlobalAgentProfileByName(ctx context.Context, name string) (AgentProfile, error) {
	row := q.db.QueryRowContext(ctx, getGlobalAgentProfileByName, name)
	var i AgentProfile
	err := row.Scan(
		&i.ProfileID,
		&i.WorkspaceID,
		&i.Name,
		&i.Harness,
		&i.Model,
		&i.Prompt,
		&i.InvocationClass,
		&i.DefaultsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceAgentProfileByName = `-- name: GetWorkspaceAgentProfileByName :one
SELECT
  profile_id,
  workspace_id,
  name,
  harness,
  model,
  prompt,
  invocation_class,
  defaults_json,
  created_at,
  updated_at
FROM agent_profiles
WHERE workspace_id = ? AND name = ?
LIMIT 1
`

type GetWorkspaceAgentProfileByNameParams struct {
	WorkspaceID sql.NullString `json:"workspace_id"`
	Name        string         `json:"name"`
}

func (q *Queries) GetWorkspaceAgentProfileByName(ctx context.Context, arg GetWorkspaceAgentProfileByNameParams) (AgentProfile, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceAgentProfileByName, arg.WorkspaceID, arg.Name)
	var i AgentProfile
	err := row.Scan(
		&i.ProfileID,
		&i.WorkspaceID,
		&i.Name,
		&i.Harness,
		&i.Model,
		&i.Prompt,
		&i.InvocationClass,
		&i.DefaultsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGlobalAgentProfiles = `-- name: ListGlobalAgentProfiles :many
SELECT
  profile_id,
  workspace_id,
  name,
  harness,
  model,
  prompt,
  invocation_class,
  defaults_json,
  created_at,
  updated_at
FROM agent_profiles
WHERE workspace_id IS NULL
ORDER BY name ASC, profile_id ASC
`

func (q *Queries) ListGlobalAgentProfiles(ctx context.Context) ([]AgentProfile, error) {
	rows, err := q.db.QueryContext(ctx, listGlobalAgentProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentProfile{}
	for rows.Next() {
		var i AgentProfile
		if err := rows.Scan(
			&i.ProfileID,
			&i.WorkspaceID,
			&i.Name,
			&i.Harness,
			&i.Model,
			&i.Prompt,
			&i.InvocationClass,
			&i.DefaultsJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceAgentProfiles = `-- name: ListWorkspaceAgentProfiles :many
SELECT
  profile_id,
  workspace_id,
  name,
  harness,
  model,
  prompt,
  invocation_class,
  defaults_json,
  created_at,
  updated_at
FROM agent_profiles
WHERE workspace_id = ?
ORDER BY name ASC, profile_id ASC
`

func (q *Queries) ListWorkspaceAgentProfiles(ctx context.Context, workspaceID sql.NullString) ([]AgentProfile, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaceAgentProfiles, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentProfile{}
	for rows.Next() {
		var i AgentProfile
		if err := rows.Scan(
			&i.ProfileID,
			&i.WorkspaceID,
			&i.Name,
			&i.Harness,
			&i.Model,
			&i.Prompt,
			&i.InvocationClass,
			&i.DefaultsJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAgentProfile = `-- name: UpsertAgentProfile :exec
INSERT INTO agent_profiles (
  profile_id,
  workspace_id,
  name,
  harness,
  model,
  prompt,
  invocation_class,
  defaults_json,
  created_at,
  updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(profile_id) DO UPDATE SET
  workspace_id = excluded.workspace_id,
  name = excluded.name,
  harness = excluded.harness,
  model = excluded.model,
  prompt = excluded.prompt,
  invocation_class = excluded.invocation_class,
  defaults_json = excluded.defaults_json,
  updated_at = excluded.updated_at
`

type UpsertAgentProfileParams struct {
	ProfileID       string         `json:"profile_id"`
	WorkspaceID     sql.NullString `json:"workspace_id"`
	Name            string         `json:"name"`
	Harness         sql.NullString `json:"harness"`
	Model           sql.NullString `json:"model"`
	Prompt          sql.NullString `json:"prompt"`
	InvocationClass sql.NullString `json:"invocation_class"`
	DefaultsJson    string         `json:"defaults_json"`
	CreatedAt       string         `json:"created_at"`
	UpdatedAt       string         `json:"updated_at"`
}

func (q *Queries) UpsertAgentProfile(ctx context.Context, arg UpsertAgentProfileParams) error {
	_, err := q.db.ExecContext(ctx, upsertAgentProfile,
		arg.ProfileID,
		arg.WorkspaceID,
		arg.Name,
		arg.Harness,
		arg.Model,
		arg.Prompt,
		arg.InvocationClass,
		arg.DefaultsJson,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
