// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: agent_runtime.sql

package dbsqlc

import (
	"context"
)

const appendRunLogMessage = `-- name: AppendRunLogMessage :exec
INSERT INTO run_log_messages (
  message_id,
  workspace_id,
  session_id,
  agent_id,
  sequence,
  role,
  status,
  provider_message_id,
  provider_item_id,
  provider_turn_id,
  provider_response_id,
  provider_call_id,
  provider_channel,
  provider_kind,
  raw_metadata_json
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type AppendRunLogMessageParams struct {
	MessageID          string `json:"message_id"`
	WorkspaceID        string `json:"workspace_id"`
	SessionID          string `json:"session_id"`
	AgentID            string `json:"agent_id"`
	Sequence           int64  `json:"sequence"`
	Role               string `json:"role"`
	Status             string `json:"status"`
	ProviderMessageID  string `json:"provider_message_id"`
	ProviderItemID     string `json:"provider_item_id"`
	ProviderTurnID     string `json:"provider_turn_id"`
	ProviderResponseID string `json:"provider_response_id"`
	ProviderCallID     string `json:"provider_call_id"`
	ProviderChannel    string `json:"provider_channel"`
	ProviderKind       string `json:"provider_kind"`
	RawMetadataJson    string `json:"raw_metadata_json"`
}

func (q *Queries) AppendRunLogMessage(ctx context.Context, arg AppendRunLogMessageParams) error {
	_, err := q.db.ExecContext(ctx, appendRunLogMessage,
		arg.MessageID,
		arg.WorkspaceID,
		arg.SessionID,
		arg.AgentID,
		arg.Sequence,
		arg.Role,
		arg.Status,
		arg.ProviderMessageID,
		arg.ProviderItemID,
		arg.ProviderTurnID,
		arg.ProviderResponseID,
		arg.ProviderCallID,
		arg.ProviderChannel,
		arg.ProviderKind,
		arg.RawMetadataJson,
	)
	return err
}

const appendRunLogMessagePart = `-- name: AppendRunLogMessagePart :exec
INSERT INTO run_log_message_parts (
  part_id,
  message_id,
  sequence,
  kind,
  text,
  mime_type,
  uri,
  name,
  tool_name,
  tool_call_id,
  raw_json
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type AppendRunLogMessagePartParams struct {
	PartID     string `json:"part_id"`
	MessageID  string `json:"message_id"`
	Sequence   int64  `json:"sequence"`
	Kind       string `json:"kind"`
	Text       string `json:"text"`
	MimeType   string `json:"mime_type"`
	Uri        string `json:"uri"`
	Name       string `json:"name"`
	ToolName   string `json:"tool_name"`
	ToolCallID string `json:"tool_call_id"`
	RawJson    string `json:"raw_json"`
}

func (q *Queries) AppendRunLogMessagePart(ctx context.Context, arg AppendRunLogMessagePartParams) error {
	_, err := q.db.ExecContext(ctx, appendRunLogMessagePart,
		arg.PartID,
		arg.MessageID,
		arg.Sequence,
		arg.Kind,
		arg.Text,
		arg.MimeType,
		arg.Uri,
		arg.Name,
		arg.ToolName,
		arg.ToolCallID,
		arg.RawJson,
	)
	return err
}

const createAgentMessage = `-- name: CreateAgentMessage :exec
INSERT INTO agent_messages (
  agent_message_id,
  workspace_id,
  source_agent_id,
  source_session_id,
  target_agent_id,
  target_session_id,
  body,
  status,
  delivered_session_id
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateAgentMessageParams struct {
	AgentMessageID     string `json:"agent_message_id"`
	WorkspaceID        string `json:"workspace_id"`
	SourceAgentID      string `json:"source_agent_id"`
	SourceSessionID    string `json:"source_session_id"`
	TargetAgentID      string `json:"target_agent_id"`
	TargetSessionID    string `json:"target_session_id"`
	Body               string `json:"body"`
	Status             string `json:"status"`
	DeliveredSessionID string `json:"delivered_session_id"`
}

func (q *Queries) CreateAgentMessage(ctx context.Context, arg CreateAgentMessageParams) error {
	_, err := q.db.ExecContext(ctx, createAgentMessage,
		arg.AgentMessageID,
		arg.WorkspaceID,
		arg.SourceAgentID,
		arg.SourceSessionID,
		arg.TargetAgentID,
		arg.TargetSessionID,
		arg.Body,
		arg.Status,
		arg.DeliveredSessionID,
	)
	return err
}

const createAgentMessageContextExcerpt = `-- name: CreateAgentMessageContextExcerpt :exec
INSERT INTO agent_message_context_excerpts (agent_message_id, context_excerpt_id, sequence)
VALUES (?, ?, ?)
`

type CreateAgentMessageContextExcerptParams struct {
	AgentMessageID   string `json:"agent_message_id"`
	ContextExcerptID string `json:"context_excerpt_id"`
	Sequence         int64  `json:"sequence"`
}

func (q *Queries) CreateAgentMessageContextExcerpt(ctx context.Context, arg CreateAgentMessageContextExcerptParams) error {
	_, err := q.db.ExecContext(ctx, createAgentMessageContextExcerpt, arg.AgentMessageID, arg.ContextExcerptID, arg.Sequence)
	return err
}

const createAgentSession = `-- name: CreateAgentSession :exec
INSERT INTO agent_sessions (
  session_id,
  workspace_id,
  agent_id,
  harness,
  model,
  provider_session_id,
  provider_run_id,
  provider_thread_id,
  cwd,
  folder_scope_json,
  status,
  usage,
  source_session_id,
  source_agent_id,
  prompt_hash,
  context_payload_ids_json,
  permission_mode,
  sandbox_mode,
  tool_scope_json,
  provider_metadata_json
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateAgentSessionParams struct {
	SessionID             string `json:"session_id"`
	WorkspaceID           string `json:"workspace_id"`
	AgentID               string `json:"agent_id"`
	Harness               string `json:"harness"`
	Model                 string `json:"model"`
	ProviderSessionID     string `json:"provider_session_id"`
	ProviderRunID         string `json:"provider_run_id"`
	ProviderThreadID      string `json:"provider_thread_id"`
	Cwd                   string `json:"cwd"`
	FolderScopeJson       string `json:"folder_scope_json"`
	Status                string `json:"status"`
	Usage                 string `json:"usage"`
	SourceSessionID       string `json:"source_session_id"`
	SourceAgentID         string `json:"source_agent_id"`
	PromptHash            string `json:"prompt_hash"`
	ContextPayloadIdsJson string `json:"context_payload_ids_json"`
	PermissionMode        string `json:"permission_mode"`
	SandboxMode           string `json:"sandbox_mode"`
	ToolScopeJson         string `json:"tool_scope_json"`
	ProviderMetadataJson  string `json:"provider_metadata_json"`
}

func (q *Queries) CreateAgentSession(ctx context.Context, arg CreateAgentSessionParams) error {
	_, err := q.db.ExecContext(ctx, createAgentSession,
		arg.SessionID,
		arg.WorkspaceID,
		arg.AgentID,
		arg.Harness,
		arg.Model,
		arg.ProviderSessionID,
		arg.ProviderRunID,
		arg.ProviderThreadID,
		arg.Cwd,
		arg.FolderScopeJson,
		arg.Status,
		arg.Usage,
		arg.SourceSessionID,
		arg.SourceAgentID,
		arg.PromptHash,
		arg.ContextPayloadIdsJson,
		arg.PermissionMode,
		arg.SandboxMode,
		arg.ToolScopeJson,
		arg.ProviderMetadataJson,
	)
	return err
}

const createAgentSessionConfig = `-- name: CreateAgentSessionConfig :exec
INSERT INTO agent_session_configs (agent_id, workspace_id, name, harness, model, prompt)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateAgentSessionConfigParams struct {
	AgentID     string  `json:"agent_id"`
	WorkspaceID *string `json:"workspace_id"`
	Name        string  `json:"name"`
	Harness     string  `json:"harness"`
	Model       string  `json:"model"`
	Prompt      string  `json:"prompt"`
}

func (q *Queries) CreateAgentSessionConfig(ctx context.Context, arg CreateAgentSessionConfigParams) error {
	_, err := q.db.ExecContext(ctx, createAgentSessionConfig,
		arg.AgentID,
		arg.WorkspaceID,
		arg.Name,
		arg.Harness,
		arg.Model,
		arg.Prompt,
	)
	return err
}

const createContextExcerpt = `-- name: CreateContextExcerpt :exec
INSERT INTO context_excerpts (
  context_excerpt_id,
  workspace_id,
  source_session_id,
  source_agent_id,
  target_agent_id,
  selector_type,
  selector_json,
  appended_message,
  content_hash
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateContextExcerptParams struct {
	ContextExcerptID string `json:"context_excerpt_id"`
	WorkspaceID      string `json:"workspace_id"`
	SourceSessionID  string `json:"source_session_id"`
	SourceAgentID    string `json:"source_agent_id"`
	TargetAgentID    string `json:"target_agent_id"`
	SelectorType     string `json:"selector_type"`
	SelectorJson     string `json:"selector_json"`
	AppendedMessage  string `json:"appended_message"`
	ContentHash      string `json:"content_hash"`
}

func (q *Queries) CreateContextExcerpt(ctx context.Context, arg CreateContextExcerptParams) error {
	_, err := q.db.ExecContext(ctx, createContextExcerpt,
		arg.ContextExcerptID,
		arg.WorkspaceID,
		arg.SourceSessionID,
		arg.SourceAgentID,
		arg.TargetAgentID,
		arg.SelectorType,
		arg.SelectorJson,
		arg.AppendedMessage,
		arg.ContentHash,
	)
	return err
}

const createContextExcerptItem = `-- name: CreateContextExcerptItem :exec
INSERT INTO context_excerpt_items (
  context_excerpt_id,
  sequence,
  source_message_id,
  source_session_id,
  source_agent_id,
  copied_role,
  copied_text,
  copied_parts_json
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateContextExcerptItemParams struct {
	ContextExcerptID string `json:"context_excerpt_id"`
	Sequence         int64  `json:"sequence"`
	SourceMessageID  string `json:"source_message_id"`
	SourceSessionID  string `json:"source_session_id"`
	SourceAgentID    string `json:"source_agent_id"`
	CopiedRole       string `json:"copied_role"`
	CopiedText       string `json:"copied_text"`
	CopiedPartsJson  string `json:"copied_parts_json"`
}

func (q *Queries) CreateContextExcerptItem(ctx context.Context, arg CreateContextExcerptItemParams) error {
	_, err := q.db.ExecContext(ctx, createContextExcerptItem,
		arg.ContextExcerptID,
		arg.Sequence,
		arg.SourceMessageID,
		arg.SourceSessionID,
		arg.SourceAgentID,
		arg.CopiedRole,
		arg.CopiedText,
		arg.CopiedPartsJson,
	)
	return err
}

const deleteAgentSessionConfig = `-- name: DeleteAgentSessionConfig :exec
DELETE FROM agent_session_configs
WHERE agent_id = ?
`

type DeleteAgentSessionConfigParams struct {
	AgentID string `json:"agent_id"`
}

func (q *Queries) DeleteAgentSessionConfig(ctx context.Context, arg DeleteAgentSessionConfigParams) error {
	_, err := q.db.ExecContext(ctx, deleteAgentSessionConfig, arg.AgentID)
	return err
}

const ensureAgentSessionConfig = `-- name: EnsureAgentSessionConfig :exec
INSERT OR IGNORE INTO agent_session_configs (agent_id, workspace_id, name, harness, model, prompt)
VALUES (?, ?, ?, ?, ?, ?)
`

type EnsureAgentSessionConfigParams struct {
	AgentID     string  `json:"agent_id"`
	WorkspaceID *string `json:"workspace_id"`
	Name        string  `json:"name"`
	Harness     string  `json:"harness"`
	Model       string  `json:"model"`
	Prompt      string  `json:"prompt"`
}

func (q *Queries) EnsureAgentSessionConfig(ctx context.Context, arg EnsureAgentSessionConfigParams) error {
	_, err := q.db.ExecContext(ctx, ensureAgentSessionConfig,
		arg.AgentID,
		arg.WorkspaceID,
		arg.Name,
		arg.Harness,
		arg.Model,
		arg.Prompt,
	)
	return err
}

const getAgentSession = `-- name: GetAgentSession :one
SELECT session_id, workspace_id, agent_id, harness, model, provider_session_id, provider_run_id, provider_thread_id, cwd, folder_scope_json, status, usage, source_session_id, source_agent_id, prompt_hash, context_payload_ids_json, permission_mode, sandbox_mode, tool_scope_json, provider_metadata_json
FROM agent_sessions
WHERE session_id = ?
`

type GetAgentSessionParams struct {
	SessionID string `json:"session_id"`
}

type GetAgentSessionRow struct {
	SessionID             string `json:"session_id"`
	WorkspaceID           string `json:"workspace_id"`
	AgentID               string `json:"agent_id"`
	Harness               string `json:"harness"`
	Model                 string `json:"model"`
	ProviderSessionID     string `json:"provider_session_id"`
	ProviderRunID         string `json:"provider_run_id"`
	ProviderThreadID      string `json:"provider_thread_id"`
	Cwd                   string `json:"cwd"`
	FolderScopeJson       string `json:"folder_scope_json"`
	Status                string `json:"status"`
	Usage                 string `json:"usage"`
	SourceSessionID       string `json:"source_session_id"`
	SourceAgentID         string `json:"source_agent_id"`
	PromptHash            string `json:"prompt_hash"`
	ContextPayloadIdsJson string `json:"context_payload_ids_json"`
	PermissionMode        string `json:"permission_mode"`
	SandboxMode           string `json:"sandbox_mode"`
	ToolScopeJson         string `json:"tool_scope_json"`
	ProviderMetadataJson  string `json:"provider_metadata_json"`
}

func (q *Queries) GetAgentSession(ctx context.Context, arg GetAgentSessionParams) (GetAgentSessionRow, error) {
	row := q.db.QueryRowContext(ctx, getAgentSession, arg.SessionID)
	var i GetAgentSessionRow
	err := row.Scan(
		&i.SessionID,
		&i.WorkspaceID,
		&i.AgentID,
		&i.Harness,
		&i.Model,
		&i.ProviderSessionID,
		&i.ProviderRunID,
		&i.ProviderThreadID,
		&i.Cwd,
		&i.FolderScopeJson,
		&i.Status,
		&i.Usage,
		&i.SourceSessionID,
		&i.SourceAgentID,
		&i.PromptHash,
		&i.ContextPayloadIdsJson,
		&i.PermissionMode,
		&i.SandboxMode,
		&i.ToolScopeJson,
		&i.ProviderMetadataJson,
	)
	return i, err
}

const getAgentSessionConfig = `-- name: GetAgentSessionConfig :one
SELECT agent_id, workspace_id, name, harness, model, prompt
FROM agent_session_configs
WHERE agent_id = ?
`

type GetAgentSessionConfigParams struct {
	AgentID string `json:"agent_id"`
}

type GetAgentSessionConfigRow struct {
	AgentID     string  `json:"agent_id"`
	WorkspaceID *string `json:"workspace_id"`
	Name        string  `json:"name"`
	Harness     string  `json:"harness"`
	Model       string  `json:"model"`
	Prompt      string  `json:"prompt"`
}

func (q *Queries) GetAgentSessionConfig(ctx context.Context, arg GetAgentSessionConfigParams) (GetAgentSessionConfigRow, error) {
	row := q.db.QueryRowContext(ctx, getAgentSessionConfig, arg.AgentID)
	var i GetAgentSessionConfigRow
	err := row.Scan(
		&i.AgentID,
		&i.WorkspaceID,
		&i.Name,
		&i.Harness,
		&i.Model,
		&i.Prompt,
	)
	return i, err
}

const getAgentSessionIdentity = `-- name: GetAgentSessionIdentity :one
SELECT workspace_id, agent_id
FROM agent_sessions
WHERE session_id = ?
`

type GetAgentSessionIdentityParams struct {
	SessionID string `json:"session_id"`
}

type GetAgentSessionIdentityRow struct {
	WorkspaceID string `json:"workspace_id"`
	AgentID     string `json:"agent_id"`
}

func (q *Queries) GetAgentSessionIdentity(ctx context.Context, arg GetAgentSessionIdentityParams) (GetAgentSessionIdentityRow, error) {
	row := q.db.QueryRowContext(ctx, getAgentSessionIdentity, arg.SessionID)
	var i GetAgentSessionIdentityRow
	err := row.Scan(&i.WorkspaceID, &i.AgentID)
	return i, err
}

const getContextExcerpt = `-- name: GetContextExcerpt :one
SELECT
  context_excerpt_id,
  workspace_id,
  source_session_id,
  source_agent_id,
  target_agent_id,
  target_session_id,
  selector_type,
  selector_json,
  visibility,
  appended_message,
  content_hash
FROM context_excerpts
WHERE context_excerpt_id = ?
`

type GetContextExcerptParams struct {
	ContextExcerptID string `json:"context_excerpt_id"`
}

type GetContextExcerptRow struct {
	ContextExcerptID string `json:"context_excerpt_id"`
	WorkspaceID      string `json:"workspace_id"`
	SourceSessionID  string `json:"source_session_id"`
	SourceAgentID    string `json:"source_agent_id"`
	TargetAgentID    string `json:"target_agent_id"`
	TargetSessionID  string `json:"target_session_id"`
	SelectorType     string `json:"selector_type"`
	SelectorJson     string `json:"selector_json"`
	Visibility       string `json:"visibility"`
	AppendedMessage  string `json:"appended_message"`
	ContentHash      string `json:"content_hash"`
}

func (q *Queries) GetContextExcerpt(ctx context.Context, arg GetContextExcerptParams) (GetContextExcerptRow, error) {
	row := q.db.QueryRowContext(ctx, getContextExcerpt, arg.ContextExcerptID)
	var i GetContextExcerptRow
	err := row.Scan(
		&i.ContextExcerptID,
		&i.WorkspaceID,
		&i.SourceSessionID,
		&i.SourceAgentID,
		&i.TargetAgentID,
		&i.TargetSessionID,
		&i.SelectorType,
		&i.SelectorJson,
		&i.Visibility,
		&i.AppendedMessage,
		&i.ContentHash,
	)
	return i, err
}

const listAgentSessionConfigs = `-- name: ListAgentSessionConfigs :many
SELECT agent_id, workspace_id, name, harness, model, prompt
FROM agent_session_configs
WHERE workspace_id = ?
ORDER BY name ASC, agent_id ASC
`

type ListAgentSessionConfigsParams struct {
	WorkspaceID *string `json:"workspace_id"`
}

type ListAgentSessionConfigsRow struct {
	AgentID     string  `json:"agent_id"`
	WorkspaceID *string `json:"workspace_id"`
	Name        string  `json:"name"`
	Harness     string  `json:"harness"`
	Model       string  `json:"model"`
	Prompt      string  `json:"prompt"`
}

func (q *Queries) ListAgentSessionConfigs(ctx context.Context, arg ListAgentSessionConfigsParams) ([]ListAgentSessionConfigsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAgentSessionConfigs, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgentSessionConfigsRow{}
	for rows.Next() {
		var i ListAgentSessionConfigsRow
		if err := rows.Scan(
			&i.AgentID,
			&i.WorkspaceID,
			&i.Name,
			&i.Harness,
			&i.Model,
			&i.Prompt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentSessions = `-- name: ListAgentSessions :many
SELECT session_id, workspace_id, agent_id, harness, model, provider_session_id, provider_run_id, provider_thread_id, cwd, folder_scope_json, status, usage, source_session_id, source_agent_id, prompt_hash, context_payload_ids_json, permission_mode, sandbox_mode, tool_scope_json, provider_metadata_json
FROM agent_sessions
WHERE workspace_id = ?
ORDER BY created_at ASC, session_id ASC
`

type ListAgentSessionsParams struct {
	WorkspaceID string `json:"workspace_id"`
}

type ListAgentSessionsRow struct {
	SessionID             string `json:"session_id"`
	WorkspaceID           string `json:"workspace_id"`
	AgentID               string `json:"agent_id"`
	Harness               string `json:"harness"`
	Model                 string `json:"model"`
	ProviderSessionID     string `json:"provider_session_id"`
	ProviderRunID         string `json:"provider_run_id"`
	ProviderThreadID      string `json:"provider_thread_id"`
	Cwd                   string `json:"cwd"`
	FolderScopeJson       string `json:"folder_scope_json"`
	Status                string `json:"status"`
	Usage                 string `json:"usage"`
	SourceSessionID       string `json:"source_session_id"`
	SourceAgentID         string `json:"source_agent_id"`
	PromptHash            string `json:"prompt_hash"`
	ContextPayloadIdsJson string `json:"context_payload_ids_json"`
	PermissionMode        string `json:"permission_mode"`
	SandboxMode           string `json:"sandbox_mode"`
	ToolScopeJson         string `json:"tool_scope_json"`
	ProviderMetadataJson  string `json:"provider_metadata_json"`
}

func (q *Queries) ListAgentSessions(ctx context.Context, arg ListAgentSessionsParams) ([]ListAgentSessionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAgentSessions, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgentSessionsRow{}
	for rows.Next() {
		var i ListAgentSessionsRow
		if err := rows.Scan(
			&i.SessionID,
			&i.WorkspaceID,
			&i.AgentID,
			&i.Harness,
			&i.Model,
			&i.ProviderSessionID,
			&i.ProviderRunID,
			&i.ProviderThreadID,
			&i.Cwd,
			&i.FolderScopeJson,
			&i.Status,
			&i.Usage,
			&i.SourceSessionID,
			&i.SourceAgentID,
			&i.PromptHash,
			&i.ContextPayloadIdsJson,
			&i.PermissionMode,
			&i.SandboxMode,
			&i.ToolScopeJson,
			&i.ProviderMetadataJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContextExcerptItems = `-- name: ListContextExcerptItems :many
SELECT
  sequence,
  source_message_id,
  copied_role,
  copied_text,
  copied_parts_json
FROM context_excerpt_items
WHERE context_excerpt_id = ?
ORDER BY sequence ASC
`

type ListContextExcerptItemsParams struct {
	ContextExcerptID string `json:"context_excerpt_id"`
}

type ListContextExcerptItemsRow struct {
	Sequence        int64  `json:"sequence"`
	SourceMessageID string `json:"source_message_id"`
	CopiedRole      string `json:"copied_role"`
	CopiedText      string `json:"copied_text"`
	CopiedPartsJson string `json:"copied_parts_json"`
}

func (q *Queries) ListContextExcerptItems(ctx context.Context, arg ListContextExcerptItemsParams) ([]ListContextExcerptItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listContextExcerptItems, arg.ContextExcerptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContextExcerptItemsRow{}
	for rows.Next() {
		var i ListContextExcerptItemsRow
		if err := rows.Scan(
			&i.Sequence,
			&i.SourceMessageID,
			&i.CopiedRole,
			&i.CopiedText,
			&i.CopiedPartsJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunLogMessageParts = `-- name: ListRunLogMessageParts :many
SELECT
  part_id,
  sequence,
  kind,
  text,
  mime_type,
  uri,
  name,
  tool_name,
  tool_call_id,
  raw_json
FROM run_log_message_parts
WHERE message_id = ?
ORDER BY sequence ASC, part_id ASC
`

type ListRunLogMessagePartsParams struct {
	MessageID string `json:"message_id"`
}

type ListRunLogMessagePartsRow struct {
	PartID     string `json:"part_id"`
	Sequence   int64  `json:"sequence"`
	Kind       string `json:"kind"`
	Text       string `json:"text"`
	MimeType   string `json:"mime_type"`
	Uri        string `json:"uri"`
	Name       string `json:"name"`
	ToolName   string `json:"tool_name"`
	ToolCallID string `json:"tool_call_id"`
	RawJson    string `json:"raw_json"`
}

func (q *Queries) ListRunLogMessageParts(ctx context.Context, arg ListRunLogMessagePartsParams) ([]ListRunLogMessagePartsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRunLogMessageParts, arg.MessageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunLogMessagePartsRow{}
	for rows.Next() {
		var i ListRunLogMessagePartsRow
		if err := rows.Scan(
			&i.PartID,
			&i.Sequence,
			&i.Kind,
			&i.Text,
			&i.MimeType,
			&i.Uri,
			&i.Name,
			&i.ToolName,
			&i.ToolCallID,
			&i.RawJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunLogMessages = `-- name: ListRunLogMessages :many
SELECT
  message_id,
  workspace_id,
  session_id,
  agent_id,
  sequence,
  role,
  status,
  provider_message_id,
  provider_item_id,
  provider_turn_id,
  provider_response_id,
  provider_call_id,
  provider_channel,
  provider_kind,
  raw_metadata_json
FROM run_log_messages
WHERE session_id = ? AND sequence > ?
ORDER BY sequence ASC, message_id ASC
LIMIT ?
`

type ListRunLogMessagesParams struct {
	SessionID string `json:"session_id"`
	Sequence  int64  `json:"sequence"`
	Limit     int64  `json:"limit"`
}

type ListRunLogMessagesRow struct {
	MessageID          string `json:"message_id"`
	WorkspaceID        string `json:"workspace_id"`
	SessionID          string `json:"session_id"`
	AgentID            string `json:"agent_id"`
	Sequence           int64  `json:"sequence"`
	Role               string `json:"role"`
	Status             string `json:"status"`
	ProviderMessageID  string `json:"provider_message_id"`
	ProviderItemID     string `json:"provider_item_id"`
	ProviderTurnID     string `json:"provider_turn_id"`
	ProviderResponseID string `json:"provider_response_id"`
	ProviderCallID     string `json:"provider_call_id"`
	ProviderChannel    string `json:"provider_channel"`
	ProviderKind       string `json:"provider_kind"`
	RawMetadataJson    string `json:"raw_metadata_json"`
}

func (q *Queries) ListRunLogMessages(ctx context.Context, arg ListRunLogMessagesParams) ([]ListRunLogMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listRunLogMessages, arg.SessionID, arg.Sequence, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunLogMessagesRow{}
	for rows.Next() {
		var i ListRunLogMessagesRow
		if err := rows.Scan(
			&i.MessageID,
			&i.WorkspaceID,
			&i.SessionID,
			&i.AgentID,
			&i.Sequence,
			&i.Role,
			&i.Status,
			&i.ProviderMessageID,
			&i.ProviderItemID,
			&i.ProviderTurnID,
			&i.ProviderResponseID,
			&i.ProviderCallID,
			&i.ProviderChannel,
			&i.ProviderKind,
			&i.RawMetadataJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextRunLogMessageSequence = `-- name: NextRunLogMessageSequence :one
SELECT CAST(COALESCE(MAX(sequence), 0) + 1 AS INTEGER) AS next_sequence
FROM run_log_messages
WHERE session_id = ?
`

type NextRunLogMessageSequenceParams struct {
	SessionID string `json:"session_id"`
}

func (q *Queries) NextRunLogMessageSequence(ctx context.Context, arg NextRunLogMessageSequenceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextRunLogMessageSequence, arg.SessionID)
	var next_sequence int64
	err := row.Scan(&next_sequence)
	return next_sequence, err
}

const tailRunLogMessages = `-- name: TailRunLogMessages :many
SELECT
  message_id,
  workspace_id,
  session_id,
  agent_id,
  sequence,
  role,
  status,
  provider_message_id,
  provider_item_id,
  provider_turn_id,
  provider_response_id,
  provider_call_id,
  provider_channel,
  provider_kind,
  raw_metadata_json
FROM (
  SELECT
    message_id,
    workspace_id,
    session_id,
    agent_id,
    sequence,
    role,
    status,
    provider_message_id,
    provider_item_id,
    provider_turn_id,
    provider_response_id,
    provider_call_id,
    provider_channel,
    provider_kind,
    raw_metadata_json
  FROM run_log_messages
  WHERE session_id = ?
  ORDER BY sequence DESC, message_id DESC
  LIMIT ?
)
ORDER BY sequence ASC, message_id ASC
`

type TailRunLogMessagesParams struct {
	SessionID string `json:"session_id"`
	Limit     int64  `json:"limit"`
}

type TailRunLogMessagesRow struct {
	MessageID          string `json:"message_id"`
	WorkspaceID        string `json:"workspace_id"`
	SessionID          string `json:"session_id"`
	AgentID            string `json:"agent_id"`
	Sequence           int64  `json:"sequence"`
	Role               string `json:"role"`
	Status             string `json:"status"`
	ProviderMessageID  string `json:"provider_message_id"`
	ProviderItemID     string `json:"provider_item_id"`
	ProviderTurnID     string `json:"provider_turn_id"`
	ProviderResponseID string `json:"provider_response_id"`
	ProviderCallID     string `json:"provider_call_id"`
	ProviderChannel    string `json:"provider_channel"`
	ProviderKind       string `json:"provider_kind"`
	RawMetadataJson    string `json:"raw_metadata_json"`
}

func (q *Queries) TailRunLogMessages(ctx context.Context, arg TailRunLogMessagesParams) ([]TailRunLogMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, tailRunLogMessages, arg.SessionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TailRunLogMessagesRow{}
	for rows.Next() {
		var i TailRunLogMessagesRow
		if err := rows.Scan(
			&i.MessageID,
			&i.WorkspaceID,
			&i.SessionID,
			&i.AgentID,
			&i.Sequence,
			&i.Role,
			&i.Status,
			&i.ProviderMessageID,
			&i.ProviderItemID,
			&i.ProviderTurnID,
			&i.ProviderResponseID,
			&i.ProviderCallID,
			&i.ProviderChannel,
			&i.ProviderKind,
			&i.RawMetadataJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgentSessionConfig = `-- name: UpdateAgentSessionConfig :exec
UPDATE agent_session_configs
SET name = ?, harness = ?, model = ?, prompt = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE agent_id = ? AND workspace_id = ?
`

type UpdateAgentSessionConfigParams struct {
	Name        string  `json:"name"`
	Harness     string  `json:"harness"`
	Model       string  `json:"model"`
	Prompt      string  `json:"prompt"`
	AgentID     string  `json:"agent_id"`
	WorkspaceID *string `json:"workspace_id"`
}

func (q *Queries) UpdateAgentSessionConfig(ctx context.Context, arg UpdateAgentSessionConfigParams) error {
	_, err := q.db.ExecContext(ctx, updateAgentSessionConfig,
		arg.Name,
		arg.Harness,
		arg.Model,
		arg.Prompt,
		arg.AgentID,
		arg.WorkspaceID,
	)
	return err
}
