// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ari_secret_grants.sql

package dbsqlc

import (
	"context"
)

const countActiveSecretGrants = `-- name: CountActiveSecretGrants :one
SELECT COUNT(*)
FROM ari_secret_grants
WHERE secret_id = ?
  AND subject_type = ?
  AND subject_id = ?
  AND purpose = ?
  AND (expires_at IS NULL OR expires_at > ?)
`

type CountActiveSecretGrantsParams struct {
	SecretID    string  `json:"secret_id"`
	SubjectType string  `json:"subject_type"`
	SubjectID   string  `json:"subject_id"`
	Purpose     string  `json:"purpose"`
	ExpiresAt   *string `json:"expires_at"`
}

func (q *Queries) CountActiveSecretGrants(ctx context.Context, arg CountActiveSecretGrantsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveSecretGrants,
		arg.SecretID,
		arg.SubjectType,
		arg.SubjectID,
		arg.Purpose,
		arg.ExpiresAt,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteSecretGrant = `-- name: DeleteSecretGrant :execrows
DELETE FROM ari_secret_grants
WHERE grant_id = ?
`

type DeleteSecretGrantParams struct {
	GrantID string `json:"grant_id"`
}

func (q *Queries) DeleteSecretGrant(ctx context.Context, arg DeleteSecretGrantParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSecretGrant, arg.GrantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSecretGrantsBySecret = `-- name: DeleteSecretGrantsBySecret :execrows
DELETE FROM ari_secret_grants
WHERE secret_id = ?
`

type DeleteSecretGrantsBySecretParams struct {
	SecretID string `json:"secret_id"`
}

func (q *Queries) DeleteSecretGrantsBySecret(ctx context.Context, arg DeleteSecretGrantsBySecretParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSecretGrantsBySecret, arg.SecretID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getSecretGrant = `-- name: GetSecretGrant :one
SELECT grant_id, secret_id, subject_type, subject_id, purpose, created_at, expires_at
FROM ari_secret_grants
WHERE grant_id = ?
`

type GetSecretGrantParams struct {
	GrantID string `json:"grant_id"`
}

func (q *Queries) GetSecretGrant(ctx context.Context, arg GetSecretGrantParams) (AriSecretGrant, error) {
	row := q.db.QueryRowContext(ctx, getSecretGrant, arg.GrantID)
	var i AriSecretGrant
	err := row.Scan(
		&i.GrantID,
		&i.SecretID,
		&i.SubjectType,
		&i.SubjectID,
		&i.Purpose,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listSecretGrantsBySubject = `-- name: ListSecretGrantsBySubject :many
SELECT grant_id, secret_id, subject_type, subject_id, purpose, created_at, expires_at
FROM ari_secret_grants
WHERE subject_type = ? AND subject_id = ?
ORDER BY created_at ASC, grant_id ASC
`

type ListSecretGrantsBySubjectParams struct {
	SubjectType string `json:"subject_type"`
	SubjectID   string `json:"subject_id"`
}

func (q *Queries) ListSecretGrantsBySubject(ctx context.Context, arg ListSecretGrantsBySubjectParams) ([]AriSecretGrant, error) {
	rows, err := q.db.QueryContext(ctx, listSecretGrantsBySubject, arg.SubjectType, arg.SubjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AriSecretGrant{}
	for rows.Next() {
		var i AriSecretGrant
		if err := rows.Scan(
			&i.GrantID,
			&i.SecretID,
			&i.SubjectType,
			&i.SubjectID,
			&i.Purpose,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSecretGrant = `-- name: UpsertSecretGrant :exec
INSERT INTO ari_secret_grants (
  grant_id, secret_id, subject_type, subject_id, purpose, created_at, expires_at
) VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(secret_id, subject_type, subject_id, purpose) DO UPDATE SET
  expires_at = excluded.expires_at
`

type UpsertSecretGrantParams struct {
	GrantID     string  `json:"grant_id"`
	SecretID    string  `json:"secret_id"`
	SubjectType string  `json:"subject_type"`
	SubjectID   string  `json:"subject_id"`
	Purpose     string  `json:"purpose"`
	CreatedAt   string  `json:"created_at"`
	ExpiresAt   *string `json:"expires_at"`
}

func (q *Queries) UpsertSecretGrant(ctx context.Context, arg UpsertSecretGrantParams) error {
	_, err := q.db.ExecContext(ctx, upsertSecretGrant,
		arg.GrantID,
		arg.SecretID,
		arg.SubjectType,
		arg.SubjectID,
		arg.Purpose,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}
