// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ari_secrets.sql

package dbsqlc

import (
	"context"
)

const deleteSecretMetadata = `-- name: DeleteSecretMetadata :execrows
DELETE FROM ari_secrets
WHERE secret_id = ?
`

type DeleteSecretMetadataParams struct {
	SecretID string `json:"secret_id"`
}

func (q *Queries) DeleteSecretMetadata(ctx context.Context, arg DeleteSecretMetadataParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSecretMetadata, arg.SecretID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getSecretMetadata = `-- name: GetSecretMetadata :one
SELECT secret_id, name, purpose, scope, backend_kind, fingerprint, redacted_description, metadata_json, created_at, updated_at
FROM ari_secrets
WHERE secret_id = ?
`

type GetSecretMetadataParams struct {
	SecretID string `json:"secret_id"`
}

func (q *Queries) GetSecretMetadata(ctx context.Context, arg GetSecretMetadataParams) (AriSecret, error) {
	row := q.db.QueryRowContext(ctx, getSecretMetadata, arg.SecretID)
	var i AriSecret
	err := row.Scan(
		&i.SecretID,
		&i.Name,
		&i.Purpose,
		&i.Scope,
		&i.BackendKind,
		&i.Fingerprint,
		&i.RedactedDescription,
		&i.MetadataJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSecretMetadata = `-- name: ListSecretMetadata :many
SELECT secret_id, name, purpose, scope, backend_kind, fingerprint, redacted_description, metadata_json, created_at, updated_at
FROM ari_secrets
ORDER BY created_at ASC, secret_id ASC
`

func (q *Queries) ListSecretMetadata(ctx context.Context) ([]AriSecret, error) {
	rows, err := q.db.QueryContext(ctx, listSecretMetadata)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AriSecret{}
	for rows.Next() {
		var i AriSecret
		if err := rows.Scan(
			&i.SecretID,
			&i.Name,
			&i.Purpose,
			&i.Scope,
			&i.BackendKind,
			&i.Fingerprint,
			&i.RedactedDescription,
			&i.MetadataJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSecretMetadataByScope = `-- name: ListSecretMetadataByScope :many
SELECT secret_id, name, purpose, scope, backend_kind, fingerprint, redacted_description, metadata_json, created_at, updated_at
FROM ari_secrets
WHERE scope = ?
ORDER BY created_at ASC, secret_id ASC
`

type ListSecretMetadataByScopeParams struct {
	Scope string `json:"scope"`
}

func (q *Queries) ListSecretMetadataByScope(ctx context.Context, arg ListSecretMetadataByScopeParams) ([]AriSecret, error) {
	rows, err := q.db.QueryContext(ctx, listSecretMetadataByScope, arg.Scope)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AriSecret{}
	for rows.Next() {
		var i AriSecret
		if err := rows.Scan(
			&i.SecretID,
			&i.Name,
			&i.Purpose,
			&i.Scope,
			&i.BackendKind,
			&i.Fingerprint,
			&i.RedactedDescription,
			&i.MetadataJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSecretMetadata = `-- name: UpsertSecretMetadata :exec
INSERT INTO ari_secrets (
  secret_id, name, purpose, scope, backend_kind, fingerprint, redacted_description, metadata_json, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(secret_id) DO UPDATE SET
  name = excluded.name,
  purpose = excluded.purpose,
  scope = excluded.scope,
  backend_kind = excluded.backend_kind,
  fingerprint = excluded.fingerprint,
  redacted_description = excluded.redacted_description,
  metadata_json = excluded.metadata_json,
  updated_at = excluded.updated_at
`

type UpsertSecretMetadataParams struct {
	SecretID            string `json:"secret_id"`
	Name                string `json:"name"`
	Purpose             string `json:"purpose"`
	Scope               string `json:"scope"`
	BackendKind         string `json:"backend_kind"`
	Fingerprint         string `json:"fingerprint"`
	RedactedDescription string `json:"redacted_description"`
	MetadataJson        string `json:"metadata_json"`
	CreatedAt           string `json:"created_at"`
	UpdatedAt           string `json:"updated_at"`
}

func (q *Queries) UpsertSecretMetadata(ctx context.Context, arg UpsertSecretMetadataParams) error {
	_, err := q.db.ExecContext(ctx, upsertSecretMetadata,
		arg.SecretID,
		arg.Name,
		arg.Purpose,
		arg.Scope,
		arg.BackendKind,
		arg.Fingerprint,
		arg.RedactedDescription,
		arg.MetadataJson,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
