// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: auth_slots.sql

package dbsqlc

import (
	"context"
)

const getAuthSlot = `-- name: GetAuthSlot :one
SELECT auth_slot_id, harness, label, provider_label, credential_owner, status, metadata_json, created_at, updated_at
FROM auth_slots
WHERE auth_slot_id = ?
`

type GetAuthSlotParams struct {
	AuthSlotID string `json:"auth_slot_id"`
}

func (q *Queries) GetAuthSlot(ctx context.Context, arg GetAuthSlotParams) (AuthSlot, error) {
	row := q.db.QueryRowContext(ctx, getAuthSlot, arg.AuthSlotID)
	var i AuthSlot
	err := row.Scan(
		&i.AuthSlotID,
		&i.Harness,
		&i.Label,
		&i.ProviderLabel,
		&i.CredentialOwner,
		&i.Status,
		&i.MetadataJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAuthSlots = `-- name: ListAuthSlots :many
SELECT auth_slot_id, harness, label, provider_label, credential_owner, status, metadata_json, created_at, updated_at
FROM auth_slots
ORDER BY harness ASC, label ASC, auth_slot_id ASC
`

func (q *Queries) ListAuthSlots(ctx context.Context) ([]AuthSlot, error) {
	rows, err := q.db.QueryContext(ctx, listAuthSlots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthSlot{}
	for rows.Next() {
		var i AuthSlot
		if err := rows.Scan(
			&i.AuthSlotID,
			&i.Harness,
			&i.Label,
			&i.ProviderLabel,
			&i.CredentialOwner,
			&i.Status,
			&i.MetadataJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuthSlotsByHarness = `-- name: ListAuthSlotsByHarness :many
SELECT auth_slot_id, harness, label, provider_label, credential_owner, status, metadata_json, created_at, updated_at
FROM auth_slots
WHERE harness = ?
ORDER BY label ASC, auth_slot_id ASC
`

type ListAuthSlotsByHarnessParams struct {
	Harness string `json:"harness"`
}

func (q *Queries) ListAuthSlotsByHarness(ctx context.Context, arg ListAuthSlotsByHarnessParams) ([]AuthSlot, error) {
	rows, err := q.db.QueryContext(ctx, listAuthSlotsByHarness, arg.Harness)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthSlot{}
	for rows.Next() {
		var i AuthSlot
		if err := rows.Scan(
			&i.AuthSlotID,
			&i.Harness,
			&i.Label,
			&i.ProviderLabel,
			&i.CredentialOwner,
			&i.Status,
			&i.MetadataJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAuthSlot = `-- name: UpsertAuthSlot :exec
INSERT INTO auth_slots (
  auth_slot_id, harness, label, provider_label, credential_owner, status, metadata_json, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(auth_slot_id) DO UPDATE SET
  harness = excluded.harness,
  label = excluded.label,
  provider_label = excluded.provider_label,
  credential_owner = excluded.credential_owner,
  status = excluded.status,
  metadata_json = excluded.metadata_json,
  updated_at = excluded.updated_at
`

type UpsertAuthSlotParams struct {
	AuthSlotID      string  `json:"auth_slot_id"`
	Harness         string  `json:"harness"`
	Label           string  `json:"label"`
	ProviderLabel   *string `json:"provider_label"`
	CredentialOwner string  `json:"credential_owner"`
	Status          string  `json:"status"`
	MetadataJson    string  `json:"metadata_json"`
	CreatedAt       string  `json:"created_at"`
	UpdatedAt       string  `json:"updated_at"`
}

func (q *Queries) UpsertAuthSlot(ctx context.Context, arg UpsertAuthSlotParams) error {
	_, err := q.db.ExecContext(ctx, upsertAuthSlot,
		arg.AuthSlotID,
		arg.Harness,
		arg.Label,
		arg.ProviderLabel,
		arg.CredentialOwner,
		arg.Status,
		arg.MetadataJson,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
