// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: commands.sql

package dbsqlc

import (
	"context"
)

const createCommand = `-- name: CreateCommand :exec
INSERT INTO commands (
  command_id, workspace_id, command, args, status, exit_code, started_at, finished_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateCommandParams struct {
	CommandID   string  `json:"command_id"`
	WorkspaceID string  `json:"workspace_id"`
	Command     string  `json:"command"`
	Args        string  `json:"args"`
	Status      string  `json:"status"`
	ExitCode    *int64  `json:"exit_code"`
	StartedAt   string  `json:"started_at"`
	FinishedAt  *string `json:"finished_at"`
}

func (q *Queries) CreateCommand(ctx context.Context, arg CreateCommandParams) error {
	_, err := q.db.ExecContext(ctx, createCommand,
		arg.CommandID,
		arg.WorkspaceID,
		arg.Command,
		arg.Args,
		arg.Status,
		arg.ExitCode,
		arg.StartedAt,
		arg.FinishedAt,
	)
	return err
}

const getCommandByID = `-- name: GetCommandByID :one
SELECT command_id, workspace_id, command, args, status, exit_code, started_at, finished_at
FROM commands
WHERE workspace_id = ? AND command_id = ?
`

type GetCommandByIDParams struct {
	WorkspaceID string `json:"workspace_id"`
	CommandID   string `json:"command_id"`
}

func (q *Queries) GetCommandByID(ctx context.Context, arg GetCommandByIDParams) (Command, error) {
	row := q.db.QueryRowContext(ctx, getCommandByID, arg.WorkspaceID, arg.CommandID)
	var i Command
	err := row.Scan(
		&i.CommandID,
		&i.WorkspaceID,
		&i.Command,
		&i.Args,
		&i.Status,
		&i.ExitCode,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listCommandsByWorkspace = `-- name: ListCommandsByWorkspace :many
SELECT command_id, workspace_id, command, args, status, exit_code, started_at, finished_at
FROM commands
WHERE workspace_id = ?
ORDER BY started_at DESC, command_id ASC
`

type ListCommandsByWorkspaceParams struct {
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) ListCommandsByWorkspace(ctx context.Context, arg ListCommandsByWorkspaceParams) ([]Command, error) {
	rows, err := q.db.QueryContext(ctx, listCommandsByWorkspace, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Command{}
	for rows.Next() {
		var i Command
		if err := rows.Scan(
			&i.CommandID,
			&i.WorkspaceID,
			&i.Command,
			&i.Args,
			&i.Status,
			&i.ExitCode,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRunningCommandsLost = `-- name: MarkRunningCommandsLost :exec
UPDATE commands
SET status = 'lost'
WHERE status = 'running'
`

func (q *Queries) MarkRunningCommandsLost(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, markRunningCommandsLost)
	return err
}

const updateCommandStatus = `-- name: UpdateCommandStatus :execrows
UPDATE commands
SET status = ?,
  exit_code = ?,
  finished_at = ?
WHERE workspace_id = ? AND command_id = ?
`

type UpdateCommandStatusParams struct {
	Status      string  `json:"status"`
	ExitCode    *int64  `json:"exit_code"`
	FinishedAt  *string `json:"finished_at"`
	WorkspaceID string  `json:"workspace_id"`
	CommandID   string  `json:"command_id"`
}

func (q *Queries) UpdateCommandStatus(ctx context.Context, arg UpdateCommandStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateCommandStatus,
		arg.Status,
		arg.ExitCode,
		arg.FinishedAt,
		arg.WorkspaceID,
		arg.CommandID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
