// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: daemon_events.sql

package dbsqlc

import (
	"context"
)

const clearDaemonEventAttention = `-- name: ClearDaemonEventAttention :execrows
UPDATE daemon_events
SET attention_cleared_at = ?
WHERE event_id = ? AND attention_required = 1 AND attention_cleared_at IS NULL
`

type ClearDaemonEventAttentionParams struct {
	AttentionClearedAt *string `json:"attention_cleared_at"`
	EventID            string  `json:"event_id"`
}

func (q *Queries) ClearDaemonEventAttention(ctx context.Context, arg ClearDaemonEventAttentionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, clearDaemonEventAttention, arg.AttentionClearedAt, arg.EventID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countDaemonEventsByID = `-- name: CountDaemonEventsByID :one
SELECT count(*)
FROM daemon_events
WHERE event_id = ?
`

type CountDaemonEventsByIDParams struct {
	EventID string `json:"event_id"`
}

func (q *Queries) CountDaemonEventsByID(ctx context.Context, arg CountDaemonEventsByIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDaemonEventsByID, arg.EventID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDaemonEvent = `-- name: CreateDaemonEvent :exec
INSERT INTO daemon_events (
  event_id,
  workspace_id,
  session_id,
  event_type,
  subject_type,
  subject_id,
  payload_json,
  attention_required,
  attention_cleared_at,
  created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateDaemonEventParams struct {
	EventID            string  `json:"event_id"`
	WorkspaceID        *string `json:"workspace_id"`
	SessionID          *string `json:"session_id"`
	EventType          string  `json:"event_type"`
	SubjectType        string  `json:"subject_type"`
	SubjectID          string  `json:"subject_id"`
	PayloadJson        string  `json:"payload_json"`
	AttentionRequired  int64   `json:"attention_required"`
	AttentionClearedAt *string `json:"attention_cleared_at"`
	CreatedAt          string  `json:"created_at"`
}

func (q *Queries) CreateDaemonEvent(ctx context.Context, arg CreateDaemonEventParams) error {
	_, err := q.db.ExecContext(ctx, createDaemonEvent,
		arg.EventID,
		arg.WorkspaceID,
		arg.SessionID,
		arg.EventType,
		arg.SubjectType,
		arg.SubjectID,
		arg.PayloadJson,
		arg.AttentionRequired,
		arg.AttentionClearedAt,
		arg.CreatedAt,
	)
	return err
}

const listDaemonAttentionEvents = `-- name: ListDaemonAttentionEvents :many
SELECT event_id, workspace_id, session_id, event_type, subject_type, subject_id, payload_json, attention_required, attention_cleared_at, created_at
FROM daemon_events
WHERE attention_required = 1 AND attention_cleared_at IS NULL
ORDER BY created_at ASC, event_id ASC
`

func (q *Queries) ListDaemonAttentionEvents(ctx context.Context) ([]DaemonEvent, error) {
	rows, err := q.db.QueryContext(ctx, listDaemonAttentionEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DaemonEvent{}
	for rows.Next() {
		var i DaemonEvent
		if err := rows.Scan(
			&i.EventID,
			&i.WorkspaceID,
			&i.SessionID,
			&i.EventType,
			&i.SubjectType,
			&i.SubjectID,
			&i.PayloadJson,
			&i.AttentionRequired,
			&i.AttentionClearedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDaemonEventsAfter = `-- name: ListDaemonEventsAfter :many
SELECT event_id, workspace_id, session_id, event_type, subject_type, subject_id, payload_json, attention_required, attention_cleared_at, created_at
FROM daemon_events AS event
WHERE event.created_at > (SELECT cursor.created_at FROM daemon_events AS cursor WHERE cursor.event_id = ?)
   OR (? = '')
   OR (event.created_at = (SELECT cursor.created_at FROM daemon_events AS cursor WHERE cursor.event_id = ?) AND event.event_id > ?)
ORDER BY event.created_at ASC, event.event_id ASC
LIMIT ?
`

type ListDaemonEventsAfterParams struct {
	EventID   string      `json:"event_id"`
	Column2   interface{} `json:"column_2"`
	EventID_2 string      `json:"event_id_2"`
	EventID_3 string      `json:"event_id_3"`
	Limit     int64       `json:"limit"`
}

func (q *Queries) ListDaemonEventsAfter(ctx context.Context, arg ListDaemonEventsAfterParams) ([]DaemonEvent, error) {
	rows, err := q.db.QueryContext(ctx, listDaemonEventsAfter,
		arg.EventID,
		arg.Column2,
		arg.EventID_2,
		arg.EventID_3,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DaemonEvent{}
	for rows.Next() {
		var i DaemonEvent
		if err := rows.Scan(
			&i.EventID,
			&i.WorkspaceID,
			&i.SessionID,
			&i.EventType,
			&i.SubjectType,
			&i.SubjectID,
			&i.PayloadJson,
			&i.AttentionRequired,
			&i.AttentionClearedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
