// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fanout_groups.sql

package dbsqlc

import (
	"context"
)

const createFanoutGroup = `-- name: CreateFanoutGroup :exec
INSERT INTO fanout_groups (
  fanout_group_id,
  workspace_id,
  source_session_id,
  source_agent_id,
  request_agent_message_id,
  status,
  body,
  created_at,
  updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateFanoutGroupParams struct {
	FanoutGroupID         string `json:"fanout_group_id"`
	WorkspaceID           string `json:"workspace_id"`
	SourceSessionID       string `json:"source_session_id"`
	SourceAgentID         string `json:"source_agent_id"`
	RequestAgentMessageID string `json:"request_agent_message_id"`
	Status                string `json:"status"`
	Body                  string `json:"body"`
	CreatedAt             string `json:"created_at"`
	UpdatedAt             string `json:"updated_at"`
}

func (q *Queries) CreateFanoutGroup(ctx context.Context, arg CreateFanoutGroupParams) error {
	_, err := q.db.ExecContext(ctx, createFanoutGroup,
		arg.FanoutGroupID,
		arg.WorkspaceID,
		arg.SourceSessionID,
		arg.SourceAgentID,
		arg.RequestAgentMessageID,
		arg.Status,
		arg.Body,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getFanoutGroup = `-- name: GetFanoutGroup :one
SELECT fanout_group_id, workspace_id, source_session_id, source_agent_id, request_agent_message_id, status, body, created_at, updated_at
FROM fanout_groups
WHERE fanout_group_id = ?
`

type GetFanoutGroupParams struct {
	FanoutGroupID string `json:"fanout_group_id"`
}

func (q *Queries) GetFanoutGroup(ctx context.Context, arg GetFanoutGroupParams) (FanoutGroup, error) {
	row := q.db.QueryRowContext(ctx, getFanoutGroup, arg.FanoutGroupID)
	var i FanoutGroup
	err := row.Scan(
		&i.FanoutGroupID,
		&i.WorkspaceID,
		&i.SourceSessionID,
		&i.SourceAgentID,
		&i.RequestAgentMessageID,
		&i.Status,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
