// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: final_responses.sql

package dbsqlc

import (
	"context"
)

const getFinalResponseByID = `-- name: GetFinalResponseByID :one
SELECT
  final_response_id,
  run_id,
  workspace_id,
  task_id,
  context_packet_id,
  profile_id,
  status,
  text,
  evidence_links,
  created_at,
  updated_at
FROM final_responses
WHERE final_response_id = ?
LIMIT 1
`

type GetFinalResponseByIDParams struct {
	FinalResponseID string `json:"final_response_id"`
}

func (q *Queries) GetFinalResponseByID(ctx context.Context, arg GetFinalResponseByIDParams) (FinalResponse, error) {
	row := q.db.QueryRowContext(ctx, getFinalResponseByID, arg.FinalResponseID)
	var i FinalResponse
	err := row.Scan(
		&i.FinalResponseID,
		&i.RunID,
		&i.WorkspaceID,
		&i.TaskID,
		&i.ContextPacketID,
		&i.ProfileID,
		&i.Status,
		&i.Text,
		&i.EvidenceLinks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFinalResponseByRunID = `-- name: GetFinalResponseByRunID :one
SELECT
  final_response_id,
  run_id,
  workspace_id,
  task_id,
  context_packet_id,
  profile_id,
  status,
  text,
  evidence_links,
  created_at,
  updated_at
FROM final_responses
WHERE run_id = ?
LIMIT 1
`

type GetFinalResponseByRunIDParams struct {
	RunID string `json:"run_id"`
}

func (q *Queries) GetFinalResponseByRunID(ctx context.Context, arg GetFinalResponseByRunIDParams) (FinalResponse, error) {
	row := q.db.QueryRowContext(ctx, getFinalResponseByRunID, arg.RunID)
	var i FinalResponse
	err := row.Scan(
		&i.FinalResponseID,
		&i.RunID,
		&i.WorkspaceID,
		&i.TaskID,
		&i.ContextPacketID,
		&i.ProfileID,
		&i.Status,
		&i.Text,
		&i.EvidenceLinks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFinalResponsesByWorkspace = `-- name: ListFinalResponsesByWorkspace :many
SELECT
  final_response_id,
  run_id,
  workspace_id,
  task_id,
  context_packet_id,
  profile_id,
  status,
  text,
  evidence_links,
  created_at,
  updated_at
FROM final_responses
WHERE workspace_id = ?
ORDER BY created_at DESC, final_response_id ASC
`

type ListFinalResponsesByWorkspaceParams struct {
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) ListFinalResponsesByWorkspace(ctx context.Context, arg ListFinalResponsesByWorkspaceParams) ([]FinalResponse, error) {
	rows, err := q.db.QueryContext(ctx, listFinalResponsesByWorkspace, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FinalResponse{}
	for rows.Next() {
		var i FinalResponse
		if err := rows.Scan(
			&i.FinalResponseID,
			&i.RunID,
			&i.WorkspaceID,
			&i.TaskID,
			&i.ContextPacketID,
			&i.ProfileID,
			&i.Status,
			&i.Text,
			&i.EvidenceLinks,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFinalResponse = `-- name: UpsertFinalResponse :exec
INSERT INTO final_responses (
  final_response_id,
  run_id,
  workspace_id,
  task_id,
  context_packet_id,
  profile_id,
  status,
  text,
  evidence_links,
  created_at,
  updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(run_id) DO UPDATE SET
  status = excluded.status,
  text = excluded.text,
  evidence_links = excluded.evidence_links,
  updated_at = excluded.updated_at
`

type UpsertFinalResponseParams struct {
	FinalResponseID string  `json:"final_response_id"`
	RunID           string  `json:"run_id"`
	WorkspaceID     string  `json:"workspace_id"`
	TaskID          string  `json:"task_id"`
	ContextPacketID string  `json:"context_packet_id"`
	ProfileID       *string `json:"profile_id"`
	Status          string  `json:"status"`
	Text            string  `json:"text"`
	EvidenceLinks   string  `json:"evidence_links"`
	CreatedAt       string  `json:"created_at"`
	UpdatedAt       *string `json:"updated_at"`
}

func (q *Queries) UpsertFinalResponse(ctx context.Context, arg UpsertFinalResponseParams) error {
	_, err := q.db.ExecContext(ctx, upsertFinalResponse,
		arg.FinalResponseID,
		arg.RunID,
		arg.WorkspaceID,
		arg.TaskID,
		arg.ContextPacketID,
		arg.ProfileID,
		arg.Status,
		arg.Text,
		arg.EvidenceLinks,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
