// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inbox_items.sql

package dbsqlc

import (
	"context"
)

const countInboxItemsBySession = `-- name: CountInboxItemsBySession :one
SELECT
  COUNT(*) AS total_count,
  COALESCE(SUM(CASE WHEN status = 'unread' THEN 1 ELSE 0 END), 0) AS unread_count,
  COALESCE(SUM(CASE WHEN status = 'read' THEN 1 ELSE 0 END), 0) AS read_count
FROM inbox_items
WHERE workspace_id = ? AND source_session_id = ?
`

type CountInboxItemsBySessionParams struct {
	WorkspaceID     string `json:"workspace_id"`
	SourceSessionID string `json:"source_session_id"`
}

type CountInboxItemsBySessionRow struct {
	TotalCount  int64       `json:"total_count"`
	UnreadCount interface{} `json:"unread_count"`
	ReadCount   interface{} `json:"read_count"`
}

func (q *Queries) CountInboxItemsBySession(ctx context.Context, arg CountInboxItemsBySessionParams) (CountInboxItemsBySessionRow, error) {
	row := q.db.QueryRowContext(ctx, countInboxItemsBySession, arg.WorkspaceID, arg.SourceSessionID)
	var i CountInboxItemsBySessionRow
	err := row.Scan(&i.TotalCount, &i.UnreadCount, &i.ReadCount)
	return i, err
}

const createInboxItem = `-- name: CreateInboxItem :exec
INSERT INTO inbox_items (
  inbox_item_id,
  workspace_id,
  source_session_id,
  workspace_event_id,
  event_type,
  fanout_group_id,
  fanout_member_id,
  worker_session_id,
  final_response_id,
  kind,
  status,
  attention_required,
  summary,
  created_at,
  updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(inbox_item_id) DO UPDATE SET
  workspace_id = excluded.workspace_id,
  source_session_id = excluded.source_session_id,
  workspace_event_id = excluded.workspace_event_id,
  event_type = excluded.event_type,
  fanout_group_id = excluded.fanout_group_id,
  fanout_member_id = excluded.fanout_member_id,
  worker_session_id = excluded.worker_session_id,
  final_response_id = excluded.final_response_id,
  kind = excluded.kind,
  status = inbox_items.status,
  attention_required = excluded.attention_required,
  summary = excluded.summary,
  updated_at = excluded.updated_at
`

type CreateInboxItemParams struct {
	InboxItemID       string `json:"inbox_item_id"`
	WorkspaceID       string `json:"workspace_id"`
	SourceSessionID   string `json:"source_session_id"`
	WorkspaceEventID  string `json:"workspace_event_id"`
	EventType         string `json:"event_type"`
	FanoutGroupID     string `json:"fanout_group_id"`
	FanoutMemberID    string `json:"fanout_member_id"`
	WorkerSessionID   string `json:"worker_session_id"`
	FinalResponseID   string `json:"final_response_id"`
	Kind              string `json:"kind"`
	Status            string `json:"status"`
	AttentionRequired int64  `json:"attention_required"`
	Summary           string `json:"summary"`
	CreatedAt         string `json:"created_at"`
	UpdatedAt         string `json:"updated_at"`
}

func (q *Queries) CreateInboxItem(ctx context.Context, arg CreateInboxItemParams) error {
	_, err := q.db.ExecContext(ctx, createInboxItem,
		arg.InboxItemID,
		arg.WorkspaceID,
		arg.SourceSessionID,
		arg.WorkspaceEventID,
		arg.EventType,
		arg.FanoutGroupID,
		arg.FanoutMemberID,
		arg.WorkerSessionID,
		arg.FinalResponseID,
		arg.Kind,
		arg.Status,
		arg.AttentionRequired,
		arg.Summary,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getInboxItem = `-- name: GetInboxItem :one
SELECT inbox_item_id, workspace_id, source_session_id, workspace_event_id, event_type, fanout_group_id, fanout_member_id, worker_session_id, final_response_id, kind, status, attention_required, summary, created_at, updated_at
FROM inbox_items
WHERE inbox_item_id = ?
`

type GetInboxItemParams struct {
	InboxItemID string `json:"inbox_item_id"`
}

func (q *Queries) GetInboxItem(ctx context.Context, arg GetInboxItemParams) (InboxItem, error) {
	row := q.db.QueryRowContext(ctx, getInboxItem, arg.InboxItemID)
	var i InboxItem
	err := row.Scan(
		&i.InboxItemID,
		&i.WorkspaceID,
		&i.SourceSessionID,
		&i.WorkspaceEventID,
		&i.EventType,
		&i.FanoutGroupID,
		&i.FanoutMemberID,
		&i.WorkerSessionID,
		&i.FinalResponseID,
		&i.Kind,
		&i.Status,
		&i.AttentionRequired,
		&i.Summary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInboxItemsBySession = `-- name: ListInboxItemsBySession :many
SELECT inbox_item_id, workspace_id, source_session_id, workspace_event_id, event_type, fanout_group_id, fanout_member_id, worker_session_id, final_response_id, kind, status, attention_required, summary, created_at, updated_at
FROM inbox_items
WHERE workspace_id = ? AND source_session_id = ?
ORDER BY created_at DESC, inbox_item_id ASC
`

type ListInboxItemsBySessionParams struct {
	WorkspaceID     string `json:"workspace_id"`
	SourceSessionID string `json:"source_session_id"`
}

func (q *Queries) ListInboxItemsBySession(ctx context.Context, arg ListInboxItemsBySessionParams) ([]InboxItem, error) {
	rows, err := q.db.QueryContext(ctx, listInboxItemsBySession, arg.WorkspaceID, arg.SourceSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InboxItem{}
	for rows.Next() {
		var i InboxItem
		if err := rows.Scan(
			&i.InboxItemID,
			&i.WorkspaceID,
			&i.SourceSessionID,
			&i.WorkspaceEventID,
			&i.EventType,
			&i.FanoutGroupID,
			&i.FanoutMemberID,
			&i.WorkerSessionID,
			&i.FinalResponseID,
			&i.Kind,
			&i.Status,
			&i.AttentionRequired,
			&i.Summary,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInboxItemRead = `-- name: MarkInboxItemRead :execrows
UPDATE inbox_items
SET status = 'read',
    updated_at = ?
WHERE workspace_id = ? AND source_session_id = ? AND inbox_item_id = ? AND status != 'read'
`

type MarkInboxItemReadParams struct {
	UpdatedAt       string `json:"updated_at"`
	WorkspaceID     string `json:"workspace_id"`
	SourceSessionID string `json:"source_session_id"`
	InboxItemID     string `json:"inbox_item_id"`
}

func (q *Queries) MarkInboxItemRead(ctx context.Context, arg MarkInboxItemReadParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markInboxItemRead,
		arg.UpdatedAt,
		arg.WorkspaceID,
		arg.SourceSessionID,
		arg.InboxItemID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
