// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: meta.sql

package dbsqlc

import (
	"context"
)

const compareAndSwapMeta = `-- name: CompareAndSwapMeta :execrows
UPDATE daemon_meta
SET value = ?
WHERE key = ?
  AND value = ?
`

type CompareAndSwapMetaParams struct {
	Value   string `json:"value"`
	Key     string `json:"key"`
	Value_2 string `json:"value_2"`
}

func (q *Queries) CompareAndSwapMeta(ctx context.Context, arg CompareAndSwapMetaParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, compareAndSwapMeta, arg.Value, arg.Key, arg.Value_2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getMetaValue = `-- name: GetMetaValue :one
SELECT value FROM daemon_meta WHERE key = ?
`

type GetMetaValueParams struct {
	Key string `json:"key"`
}

func (q *Queries) GetMetaValue(ctx context.Context, arg GetMetaValueParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getMetaValue, arg.Key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const upsertMeta = `-- name: UpsertMeta :exec
INSERT INTO daemon_meta (key, value)
VALUES (?, ?)
ON CONFLICT(key) DO UPDATE SET
  value = excluded.value
`

type UpsertMetaParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) UpsertMeta(ctx context.Context, arg UpsertMetaParams) error {
	_, err := q.db.ExecContext(ctx, upsertMeta, arg.Key, arg.Value)
	return err
}
