// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package dbsqlc

type Agent struct {
	AgentID            string  `json:"agent_id"`
	WorkspaceID        string  `json:"workspace_id"`
	Name               *string `json:"name"`
	Command            string  `json:"command"`
	Args               string  `json:"args"`
	Status             string  `json:"status"`
	ExitCode           *int64  `json:"exit_code"`
	StartedAt          string  `json:"started_at"`
	StoppedAt          *string `json:"stopped_at"`
	Harness            *string `json:"harness"`
	HarnessResumableID *string `json:"harness_resumable_id"`
	HarnessMetadata    string  `json:"harness_metadata"`
	InvocationClass    string  `json:"invocation_class"`
}

type AgentProfile struct {
	ProfileID       string  `json:"profile_id"`
	WorkspaceID     *string `json:"workspace_id"`
	Name            string  `json:"name"`
	Harness         *string `json:"harness"`
	Model           *string `json:"model"`
	Prompt          *string `json:"prompt"`
	InvocationClass *string `json:"invocation_class"`
	DefaultsJson    string  `json:"defaults_json"`
	CreatedAt       string  `json:"created_at"`
	UpdatedAt       string  `json:"updated_at"`
}

type AgentRunTelemetry struct {
	RunID                   string  `json:"run_id"`
	WorkspaceID             string  `json:"workspace_id"`
	TaskID                  string  `json:"task_id"`
	ProfileID               *string `json:"profile_id"`
	ProfileName             *string `json:"profile_name"`
	Harness                 string  `json:"harness"`
	Model                   string  `json:"model"`
	InvocationClass         string  `json:"invocation_class"`
	Status                  string  `json:"status"`
	InputTokensKnown        int64   `json:"input_tokens_known"`
	InputTokens             *int64  `json:"input_tokens"`
	OutputTokensKnown       int64   `json:"output_tokens_known"`
	OutputTokens            *int64  `json:"output_tokens"`
	EstimatedCostKnown      int64   `json:"estimated_cost_known"`
	EstimatedCostMicros     *int64  `json:"estimated_cost_micros"`
	DurationMsKnown         int64   `json:"duration_ms_known"`
	DurationMs              *int64  `json:"duration_ms"`
	ExitCodeKnown           int64   `json:"exit_code_known"`
	ExitCode                *int64  `json:"exit_code"`
	OwnedByAri              int64   `json:"owned_by_ari"`
	PidKnown                int64   `json:"pid_known"`
	Pid                     *int64  `json:"pid"`
	CpuTimeMsKnown          int64   `json:"cpu_time_ms_known"`
	CpuTimeMs               *int64  `json:"cpu_time_ms"`
	MemoryRssBytesPeakKnown int64   `json:"memory_rss_bytes_peak_known"`
	MemoryRssBytesPeak      *int64  `json:"memory_rss_bytes_peak"`
	ChildProcessesPeakKnown int64   `json:"child_processes_peak_known"`
	ChildProcessesPeak      *int64  `json:"child_processes_peak"`
	PortsJson               string  `json:"ports_json"`
	OrphanState             string  `json:"orphan_state"`
	CreatedAt               string  `json:"created_at"`
	UpdatedAt               string  `json:"updated_at"`
}

type AuthSlot struct {
	AuthSlotID      string  `json:"auth_slot_id"`
	Harness         string  `json:"harness"`
	Label           string  `json:"label"`
	ProviderLabel   *string `json:"provider_label"`
	CredentialOwner string  `json:"credential_owner"`
	Status          string  `json:"status"`
	MetadataJson    string  `json:"metadata_json"`
	CreatedAt       string  `json:"created_at"`
	UpdatedAt       string  `json:"updated_at"`
}

type Command struct {
	CommandID   string  `json:"command_id"`
	WorkspaceID string  `json:"workspace_id"`
	Command     string  `json:"command"`
	Args        string  `json:"args"`
	Status      string  `json:"status"`
	ExitCode    *int64  `json:"exit_code"`
	StartedAt   string  `json:"started_at"`
	FinishedAt  *string `json:"finished_at"`
}

type DaemonMetum struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type FinalResponse struct {
	FinalResponseID string  `json:"final_response_id"`
	RunID           string  `json:"run_id"`
	WorkspaceID     string  `json:"workspace_id"`
	TaskID          string  `json:"task_id"`
	ContextPacketID string  `json:"context_packet_id"`
	ProfileID       *string `json:"profile_id"`
	Status          string  `json:"status"`
	Text            string  `json:"text"`
	EvidenceLinks   string  `json:"evidence_links"`
	CreatedAt       string  `json:"created_at"`
	UpdatedAt       *string `json:"updated_at"`
}

type Workspace struct {
	WorkspaceID   string `json:"workspace_id"`
	Name          string `json:"name"`
	Status        string `json:"status"`
	VcsPreference string `json:"vcs_preference"`
	OriginRoot    string `json:"origin_root"`
	CleanupPolicy string `json:"cleanup_policy"`
	CreatedAt     string `json:"created_at"`
	UpdatedAt     string `json:"updated_at"`
}

type WorkspaceCommandDefinition struct {
	CommandID   string `json:"command_id"`
	WorkspaceID string `json:"workspace_id"`
	Name        string `json:"name"`
	Command     string `json:"command"`
	Args        string `json:"args"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

type WorkspaceFolder struct {
	WorkspaceID string `json:"workspace_id"`
	FolderPath  string `json:"folder_path"`
	VcsType     string `json:"vcs_type"`
	IsPrimary   int64  `json:"is_primary"`
	AddedAt     string `json:"added_at"`
}
