// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package dbsqlc

import (
	"database/sql"
)

type Agent struct {
	AgentID            string         `json:"agent_id"`
	WorkspaceID        string         `json:"workspace_id"`
	Name               sql.NullString `json:"name"`
	Command            string         `json:"command"`
	Args               string         `json:"args"`
	Status             string         `json:"status"`
	ExitCode           sql.NullInt64  `json:"exit_code"`
	StartedAt          string         `json:"started_at"`
	StoppedAt          sql.NullString `json:"stopped_at"`
	Harness            sql.NullString `json:"harness"`
	HarnessResumableID sql.NullString `json:"harness_resumable_id"`
	HarnessMetadata    string         `json:"harness_metadata"`
	InvocationClass    string         `json:"invocation_class"`
}

type AgentProfile struct {
	ProfileID       string         `json:"profile_id"`
	WorkspaceID     sql.NullString `json:"workspace_id"`
	Name            string         `json:"name"`
	Harness         sql.NullString `json:"harness"`
	Model           sql.NullString `json:"model"`
	Prompt          sql.NullString `json:"prompt"`
	InvocationClass sql.NullString `json:"invocation_class"`
	DefaultsJson    string         `json:"defaults_json"`
	CreatedAt       string         `json:"created_at"`
	UpdatedAt       string         `json:"updated_at"`
}

type Command struct {
	CommandID   string         `json:"command_id"`
	WorkspaceID string         `json:"workspace_id"`
	Command     string         `json:"command"`
	Args        string         `json:"args"`
	Status      string         `json:"status"`
	ExitCode    sql.NullInt64  `json:"exit_code"`
	StartedAt   string         `json:"started_at"`
	FinishedAt  sql.NullString `json:"finished_at"`
}

type DaemonMetum struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type FinalResponse struct {
	FinalResponseID string         `json:"final_response_id"`
	RunID           string         `json:"run_id"`
	WorkspaceID     string         `json:"workspace_id"`
	TaskID          string         `json:"task_id"`
	ContextPacketID string         `json:"context_packet_id"`
	ProfileID       sql.NullString `json:"profile_id"`
	Status          string         `json:"status"`
	Text            string         `json:"text"`
	EvidenceLinks   string         `json:"evidence_links"`
	CreatedAt       string         `json:"created_at"`
	UpdatedAt       sql.NullString `json:"updated_at"`
}

type Workspace struct {
	WorkspaceID   string `json:"workspace_id"`
	Name          string `json:"name"`
	Status        string `json:"status"`
	VcsPreference string `json:"vcs_preference"`
	OriginRoot    string `json:"origin_root"`
	CleanupPolicy string `json:"cleanup_policy"`
	CreatedAt     string `json:"created_at"`
	UpdatedAt     string `json:"updated_at"`
}

type WorkspaceCommandDefinition struct {
	CommandID   string `json:"command_id"`
	WorkspaceID string `json:"workspace_id"`
	Name        string `json:"name"`
	Command     string `json:"command"`
	Args        string `json:"args"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

type WorkspaceFolder struct {
	WorkspaceID string `json:"workspace_id"`
	FolderPath  string `json:"folder_path"`
	VcsType     string `json:"vcs_type"`
	IsPrimary   int64  `json:"is_primary"`
	AddedAt     string `json:"added_at"`
}
