// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: operation_records.sql

package dbsqlc

import (
	"context"
)

const createOperationRecord = `-- name: CreateOperationRecord :exec
INSERT INTO operation_records (
  operation_id,
  workspace_id,
  operation_type,
  actor,
  source,
  scope,
  request_summary,
  result,
  trust_decision,
  parent_operation_id,
  checkpoint_operation_id,
  rollback_point_id,
  rollback_data_json,
  payload_hash,
  payload_snapshot_json,
  created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateOperationRecordParams struct {
	OperationID           string  `json:"operation_id"`
	WorkspaceID           *string `json:"workspace_id"`
	OperationType         string  `json:"operation_type"`
	Actor                 string  `json:"actor"`
	Source                string  `json:"source"`
	Scope                 string  `json:"scope"`
	RequestSummary        string  `json:"request_summary"`
	Result                string  `json:"result"`
	TrustDecision         *string `json:"trust_decision"`
	ParentOperationID     *string `json:"parent_operation_id"`
	CheckpointOperationID *string `json:"checkpoint_operation_id"`
	RollbackPointID       *string `json:"rollback_point_id"`
	RollbackDataJson      string  `json:"rollback_data_json"`
	PayloadHash           string  `json:"payload_hash"`
	PayloadSnapshotJson   string  `json:"payload_snapshot_json"`
	CreatedAt             string  `json:"created_at"`
}

func (q *Queries) CreateOperationRecord(ctx context.Context, arg CreateOperationRecordParams) error {
	_, err := q.db.ExecContext(ctx, createOperationRecord,
		arg.OperationID,
		arg.WorkspaceID,
		arg.OperationType,
		arg.Actor,
		arg.Source,
		arg.Scope,
		arg.RequestSummary,
		arg.Result,
		arg.TrustDecision,
		arg.ParentOperationID,
		arg.CheckpointOperationID,
		arg.RollbackPointID,
		arg.RollbackDataJson,
		arg.PayloadHash,
		arg.PayloadSnapshotJson,
		arg.CreatedAt,
	)
	return err
}

const getOperationRecord = `-- name: GetOperationRecord :one
SELECT operation_id, workspace_id, operation_type, actor, source, scope, request_summary, result, trust_decision, parent_operation_id, checkpoint_operation_id, rollback_point_id, rollback_data_json, payload_hash, payload_snapshot_json, created_at
FROM operation_records
WHERE operation_id = ?
`

type GetOperationRecordParams struct {
	OperationID string `json:"operation_id"`
}

func (q *Queries) GetOperationRecord(ctx context.Context, arg GetOperationRecordParams) (OperationRecord, error) {
	row := q.db.QueryRowContext(ctx, getOperationRecord, arg.OperationID)
	var i OperationRecord
	err := row.Scan(
		&i.OperationID,
		&i.WorkspaceID,
		&i.OperationType,
		&i.Actor,
		&i.Source,
		&i.Scope,
		&i.RequestSummary,
		&i.Result,
		&i.TrustDecision,
		&i.ParentOperationID,
		&i.CheckpointOperationID,
		&i.RollbackPointID,
		&i.RollbackDataJson,
		&i.PayloadHash,
		&i.PayloadSnapshotJson,
		&i.CreatedAt,
	)
	return i, err
}

const listOperationRecords = `-- name: ListOperationRecords :many
SELECT operation_id, workspace_id, operation_type, actor, source, scope, request_summary, result, trust_decision, parent_operation_id, checkpoint_operation_id, rollback_point_id, rollback_data_json, payload_hash, payload_snapshot_json, created_at
FROM operation_records
ORDER BY created_at DESC, operation_id ASC
`

func (q *Queries) ListOperationRecords(ctx context.Context) ([]OperationRecord, error) {
	rows, err := q.db.QueryContext(ctx, listOperationRecords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OperationRecord{}
	for rows.Next() {
		var i OperationRecord
		if err := rows.Scan(
			&i.OperationID,
			&i.WorkspaceID,
			&i.OperationType,
			&i.Actor,
			&i.Source,
			&i.Scope,
			&i.RequestSummary,
			&i.Result,
			&i.TrustDecision,
			&i.ParentOperationID,
			&i.CheckpointOperationID,
			&i.RollbackPointID,
			&i.RollbackDataJson,
			&i.PayloadHash,
			&i.PayloadSnapshotJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOperationRecordsByWorkspace = `-- name: ListOperationRecordsByWorkspace :many
SELECT operation_id, workspace_id, operation_type, actor, source, scope, request_summary, result, trust_decision, parent_operation_id, checkpoint_operation_id, rollback_point_id, rollback_data_json, payload_hash, payload_snapshot_json, created_at
FROM operation_records
WHERE workspace_id = ?
ORDER BY created_at DESC, operation_id ASC
`

type ListOperationRecordsByWorkspaceParams struct {
	WorkspaceID *string `json:"workspace_id"`
}

func (q *Queries) ListOperationRecordsByWorkspace(ctx context.Context, arg ListOperationRecordsByWorkspaceParams) ([]OperationRecord, error) {
	rows, err := q.db.QueryContext(ctx, listOperationRecordsByWorkspace, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OperationRecord{}
	for rows.Next() {
		var i OperationRecord
		if err := rows.Scan(
			&i.OperationID,
			&i.WorkspaceID,
			&i.OperationType,
			&i.Actor,
			&i.Source,
			&i.Scope,
			&i.RequestSummary,
			&i.Result,
			&i.TrustDecision,
			&i.ParentOperationID,
			&i.CheckpointOperationID,
			&i.RollbackPointID,
			&i.RollbackDataJson,
			&i.PayloadHash,
			&i.PayloadSnapshotJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
