// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pending_deliveries.sql

package dbsqlc

import (
	"context"
)

const claimDuePendingDeliveryAttempt = `-- name: ClaimDuePendingDeliveryAttempt :execrows
UPDATE pending_deliveries
SET status = 'attempted',
    attempts = attempts + 1,
    next_attempt_at = NULL,
    last_error = '',
    updated_at = ?
WHERE delivery_id = ?
  AND status = 'pending'
  AND next_attempt_at IS NOT NULL
  AND next_attempt_at <= ?
  AND (deadline_at IS NULL OR deadline_at > ?)
  AND EXISTS (
    SELECT 1
    FROM event_subscriptions es
    WHERE es.subscription_id = pending_deliveries.subscription_id
      AND es.status = 'active'
  )
`

type ClaimDuePendingDeliveryAttemptParams struct {
	UpdatedAt     string  `json:"updated_at"`
	DeliveryID    string  `json:"delivery_id"`
	NextAttemptAt *string `json:"next_attempt_at"`
	DeadlineAt    *string `json:"deadline_at"`
}

func (q *Queries) ClaimDuePendingDeliveryAttempt(ctx context.Context, arg ClaimDuePendingDeliveryAttemptParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimDuePendingDeliveryAttempt,
		arg.UpdatedAt,
		arg.DeliveryID,
		arg.NextAttemptAt,
		arg.DeadlineAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const completePendingDelivery = `-- name: CompletePendingDelivery :execrows
UPDATE pending_deliveries
SET status = 'completed',
    updated_at = ?,
    terminal_at = ?
WHERE delivery_id = ? AND status IN ('pending', 'attempted')
`

type CompletePendingDeliveryParams struct {
	UpdatedAt  string  `json:"updated_at"`
	TerminalAt *string `json:"terminal_at"`
	DeliveryID string  `json:"delivery_id"`
}

func (q *Queries) CompletePendingDelivery(ctx context.Context, arg CompletePendingDeliveryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completePendingDelivery, arg.UpdatedAt, arg.TerminalAt, arg.DeliveryID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createPendingDelivery = `-- name: CreatePendingDelivery :exec
INSERT INTO pending_deliveries (
  delivery_id,
  workspace_id,
  subscription_id,
  target_type,
  target_id,
  delivery_policy_json,
  event_ids_json,
  status,
  attempts,
  next_attempt_at,
  deadline_at,
  last_error,
  created_at,
  updated_at,
  terminal_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreatePendingDeliveryParams struct {
	DeliveryID         string  `json:"delivery_id"`
	WorkspaceID        string  `json:"workspace_id"`
	SubscriptionID     string  `json:"subscription_id"`
	TargetType         string  `json:"target_type"`
	TargetID           string  `json:"target_id"`
	DeliveryPolicyJson string  `json:"delivery_policy_json"`
	EventIdsJson       string  `json:"event_ids_json"`
	Status             string  `json:"status"`
	Attempts           int64   `json:"attempts"`
	NextAttemptAt      *string `json:"next_attempt_at"`
	DeadlineAt         *string `json:"deadline_at"`
	LastError          string  `json:"last_error"`
	CreatedAt          string  `json:"created_at"`
	UpdatedAt          string  `json:"updated_at"`
	TerminalAt         *string `json:"terminal_at"`
}

func (q *Queries) CreatePendingDelivery(ctx context.Context, arg CreatePendingDeliveryParams) error {
	_, err := q.db.ExecContext(ctx, createPendingDelivery,
		arg.DeliveryID,
		arg.WorkspaceID,
		arg.SubscriptionID,
		arg.TargetType,
		arg.TargetID,
		arg.DeliveryPolicyJson,
		arg.EventIdsJson,
		arg.Status,
		arg.Attempts,
		arg.NextAttemptAt,
		arg.DeadlineAt,
		arg.LastError,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.TerminalAt,
	)
	return err
}

const failPendingDelivery = `-- name: FailPendingDelivery :execrows
UPDATE pending_deliveries
SET status = 'failed',
    last_error = ?,
    updated_at = ?,
    terminal_at = ?
WHERE delivery_id = ? AND status IN ('pending', 'attempted')
`

type FailPendingDeliveryParams struct {
	LastError  string  `json:"last_error"`
	UpdatedAt  string  `json:"updated_at"`
	TerminalAt *string `json:"terminal_at"`
	DeliveryID string  `json:"delivery_id"`
}

func (q *Queries) FailPendingDelivery(ctx context.Context, arg FailPendingDeliveryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, failPendingDelivery,
		arg.LastError,
		arg.UpdatedAt,
		arg.TerminalAt,
		arg.DeliveryID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getPendingDelivery = `-- name: GetPendingDelivery :one
SELECT delivery_id, workspace_id, subscription_id, target_type, target_id, delivery_policy_json, event_ids_json, status, attempts, next_attempt_at, deadline_at, last_error, created_at, updated_at, terminal_at
FROM pending_deliveries
WHERE delivery_id = ?
`

type GetPendingDeliveryParams struct {
	DeliveryID string `json:"delivery_id"`
}

func (q *Queries) GetPendingDelivery(ctx context.Context, arg GetPendingDeliveryParams) (PendingDelivery, error) {
	row := q.db.QueryRowContext(ctx, getPendingDelivery, arg.DeliveryID)
	var i PendingDelivery
	err := row.Scan(
		&i.DeliveryID,
		&i.WorkspaceID,
		&i.SubscriptionID,
		&i.TargetType,
		&i.TargetID,
		&i.DeliveryPolicyJson,
		&i.EventIdsJson,
		&i.Status,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.DeadlineAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TerminalAt,
	)
	return i, err
}

const listCompletedPendingDeliveriesForSubscription = `-- name: ListCompletedPendingDeliveriesForSubscription :many
SELECT delivery_id, workspace_id, subscription_id, target_type, target_id, delivery_policy_json, event_ids_json, status, attempts, next_attempt_at, deadline_at, last_error, created_at, updated_at, terminal_at
FROM pending_deliveries
WHERE subscription_id = ? AND status = 'completed'
ORDER BY terminal_at ASC, created_at ASC, delivery_id ASC
`

type ListCompletedPendingDeliveriesForSubscriptionParams struct {
	SubscriptionID string `json:"subscription_id"`
}

func (q *Queries) ListCompletedPendingDeliveriesForSubscription(ctx context.Context, arg ListCompletedPendingDeliveriesForSubscriptionParams) ([]PendingDelivery, error) {
	rows, err := q.db.QueryContext(ctx, listCompletedPendingDeliveriesForSubscription, arg.SubscriptionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PendingDelivery{}
	for rows.Next() {
		var i PendingDelivery
		if err := rows.Scan(
			&i.DeliveryID,
			&i.WorkspaceID,
			&i.SubscriptionID,
			&i.TargetType,
			&i.TargetID,
			&i.DeliveryPolicyJson,
			&i.EventIdsJson,
			&i.Status,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.DeadlineAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TerminalAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDuePendingDeliveries = `-- name: ListDuePendingDeliveries :many
SELECT pd.delivery_id, pd.workspace_id, pd.subscription_id, pd.target_type, pd.target_id, pd.delivery_policy_json, pd.event_ids_json, pd.status, pd.attempts, pd.next_attempt_at, pd.deadline_at, pd.last_error, pd.created_at, pd.updated_at, pd.terminal_at
FROM pending_deliveries pd
JOIN event_subscriptions es ON es.subscription_id = pd.subscription_id
WHERE pd.status = 'pending'
  AND es.status = 'active'
  AND pd.next_attempt_at IS NOT NULL
  AND pd.next_attempt_at <= ?
  AND (pd.deadline_at IS NULL OR pd.deadline_at > ?)
  AND (es.timeout_at IS NULL OR es.timeout_at > ?)
ORDER BY pd.next_attempt_at ASC, pd.created_at ASC, pd.delivery_id ASC
LIMIT ?
`

type ListDuePendingDeliveriesParams struct {
	NextAttemptAt *string `json:"next_attempt_at"`
	DeadlineAt    *string `json:"deadline_at"`
	TimeoutAt     *string `json:"timeout_at"`
	Limit         int64   `json:"limit"`
}

func (q *Queries) ListDuePendingDeliveries(ctx context.Context, arg ListDuePendingDeliveriesParams) ([]PendingDelivery, error) {
	rows, err := q.db.QueryContext(ctx, listDuePendingDeliveries,
		arg.NextAttemptAt,
		arg.DeadlineAt,
		arg.TimeoutAt,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PendingDelivery{}
	for rows.Next() {
		var i PendingDelivery
		if err := rows.Scan(
			&i.DeliveryID,
			&i.WorkspaceID,
			&i.SubscriptionID,
			&i.TargetType,
			&i.TargetID,
			&i.DeliveryPolicyJson,
			&i.EventIdsJson,
			&i.Status,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.DeadlineAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TerminalAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDuePendingDeliveriesForScope = `-- name: ListDuePendingDeliveriesForScope :many
SELECT pd.delivery_id, pd.workspace_id, pd.subscription_id, pd.target_type, pd.target_id, pd.delivery_policy_json, pd.event_ids_json, pd.status, pd.attempts, pd.next_attempt_at, pd.deadline_at, pd.last_error, pd.created_at, pd.updated_at, pd.terminal_at
FROM pending_deliveries pd
JOIN event_subscriptions es ON es.subscription_id = pd.subscription_id
WHERE pd.status = 'pending'
  AND pd.workspace_id = ?
  AND es.status = 'active'
  AND (es.owner_session_id = '' OR es.owner_session_id = ?)
  AND pd.next_attempt_at IS NOT NULL
  AND pd.next_attempt_at <= ?
  AND (pd.deadline_at IS NULL OR pd.deadline_at > ?)
  AND (es.timeout_at IS NULL OR es.timeout_at > ?)
ORDER BY pd.next_attempt_at ASC, pd.created_at ASC, pd.delivery_id ASC
LIMIT ?
`

type ListDuePendingDeliveriesForScopeParams struct {
	WorkspaceID    string  `json:"workspace_id"`
	OwnerSessionID string  `json:"owner_session_id"`
	NextAttemptAt  *string `json:"next_attempt_at"`
	DeadlineAt     *string `json:"deadline_at"`
	TimeoutAt      *string `json:"timeout_at"`
	Limit          int64   `json:"limit"`
}

func (q *Queries) ListDuePendingDeliveriesForScope(ctx context.Context, arg ListDuePendingDeliveriesForScopeParams) ([]PendingDelivery, error) {
	rows, err := q.db.QueryContext(ctx, listDuePendingDeliveriesForScope,
		arg.WorkspaceID,
		arg.OwnerSessionID,
		arg.NextAttemptAt,
		arg.DeadlineAt,
		arg.TimeoutAt,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PendingDelivery{}
	for rows.Next() {
		var i PendingDelivery
		if err := rows.Scan(
			&i.DeliveryID,
			&i.WorkspaceID,
			&i.SubscriptionID,
			&i.TargetType,
			&i.TargetID,
			&i.DeliveryPolicyJson,
			&i.EventIdsJson,
			&i.Status,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.DeadlineAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TerminalAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredPendingDeliveries = `-- name: ListExpiredPendingDeliveries :many
SELECT delivery_id, workspace_id, subscription_id, target_type, target_id, delivery_policy_json, event_ids_json, status, attempts, next_attempt_at, deadline_at, last_error, created_at, updated_at, terminal_at
FROM pending_deliveries
WHERE status = 'pending'
  AND deadline_at IS NOT NULL
  AND deadline_at <= ?
ORDER BY deadline_at ASC, created_at ASC, delivery_id ASC
`

type ListExpiredPendingDeliveriesParams struct {
	DeadlineAt *string `json:"deadline_at"`
}

func (q *Queries) ListExpiredPendingDeliveries(ctx context.Context, arg ListExpiredPendingDeliveriesParams) ([]PendingDelivery, error) {
	rows, err := q.db.QueryContext(ctx, listExpiredPendingDeliveries, arg.DeadlineAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PendingDelivery{}
	for rows.Next() {
		var i PendingDelivery
		if err := rows.Scan(
			&i.DeliveryID,
			&i.WorkspaceID,
			&i.SubscriptionID,
			&i.TargetType,
			&i.TargetID,
			&i.DeliveryPolicyJson,
			&i.EventIdsJson,
			&i.Status,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.DeadlineAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TerminalAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingDeliveriesForSubscription = `-- name: ListPendingDeliveriesForSubscription :many
SELECT delivery_id, workspace_id, subscription_id, target_type, target_id, delivery_policy_json, event_ids_json, status, attempts, next_attempt_at, deadline_at, last_error, created_at, updated_at, terminal_at
FROM pending_deliveries
WHERE subscription_id = ? AND status IN ('pending', 'attempted')
ORDER BY created_at ASC, delivery_id ASC
`

type ListPendingDeliveriesForSubscriptionParams struct {
	SubscriptionID string `json:"subscription_id"`
}

func (q *Queries) ListPendingDeliveriesForSubscription(ctx context.Context, arg ListPendingDeliveriesForSubscriptionParams) ([]PendingDelivery, error) {
	rows, err := q.db.QueryContext(ctx, listPendingDeliveriesForSubscription, arg.SubscriptionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PendingDelivery{}
	for rows.Next() {
		var i PendingDelivery
		if err := rows.Scan(
			&i.DeliveryID,
			&i.WorkspaceID,
			&i.SubscriptionID,
			&i.TargetType,
			&i.TargetID,
			&i.DeliveryPolicyJson,
			&i.EventIdsJson,
			&i.Status,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.DeadlineAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TerminalAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextPendingDeliveryAttemptAt = `-- name: NextPendingDeliveryAttemptAt :one
SELECT pd.next_attempt_at
FROM pending_deliveries pd
JOIN event_subscriptions es ON es.subscription_id = pd.subscription_id
WHERE pd.status = 'pending'
  AND es.status = 'active'
  AND pd.next_attempt_at IS NOT NULL
  AND (pd.deadline_at IS NULL OR pd.deadline_at > ?)
  AND (es.timeout_at IS NULL OR es.timeout_at > ?)
ORDER BY pd.next_attempt_at ASC, pd.created_at ASC, pd.delivery_id ASC
LIMIT 1
`

type NextPendingDeliveryAttemptAtParams struct {
	DeadlineAt *string `json:"deadline_at"`
	TimeoutAt  *string `json:"timeout_at"`
}

func (q *Queries) NextPendingDeliveryAttemptAt(ctx context.Context, arg NextPendingDeliveryAttemptAtParams) (*string, error) {
	row := q.db.QueryRowContext(ctx, nextPendingDeliveryAttemptAt, arg.DeadlineAt, arg.TimeoutAt)
	var next_attempt_at *string
	err := row.Scan(&next_attempt_at)
	return next_attempt_at, err
}

const nextPendingDeliveryDeadlineAt = `-- name: NextPendingDeliveryDeadlineAt :one
SELECT deadline_at
FROM pending_deliveries
WHERE status = 'pending'
  AND deadline_at IS NOT NULL
ORDER BY deadline_at ASC, created_at ASC, delivery_id ASC
LIMIT 1
`

func (q *Queries) NextPendingDeliveryDeadlineAt(ctx context.Context) (*string, error) {
	row := q.db.QueryRowContext(ctx, nextPendingDeliveryDeadlineAt)
	var deadline_at *string
	err := row.Scan(&deadline_at)
	return deadline_at, err
}

const oldestAttemptedPendingDeliveryUpdatedAt = `-- name: OldestAttemptedPendingDeliveryUpdatedAt :one
SELECT updated_at
FROM pending_deliveries
WHERE status = 'attempted'
  AND terminal_at IS NULL
ORDER BY updated_at ASC, created_at ASC, delivery_id ASC
LIMIT 1
`

func (q *Queries) OldestAttemptedPendingDeliveryUpdatedAt(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, oldestAttemptedPendingDeliveryUpdatedAt)
	var updated_at string
	err := row.Scan(&updated_at)
	return updated_at, err
}

const recordPendingDeliveryAttempt = `-- name: RecordPendingDeliveryAttempt :execrows
UPDATE pending_deliveries
SET attempts = attempts + 1,
    next_attempt_at = ?,
    last_error = ?,
    updated_at = ?
WHERE delivery_id = ? AND status = 'pending'
`

type RecordPendingDeliveryAttemptParams struct {
	NextAttemptAt *string `json:"next_attempt_at"`
	LastError     string  `json:"last_error"`
	UpdatedAt     string  `json:"updated_at"`
	DeliveryID    string  `json:"delivery_id"`
}

func (q *Queries) RecordPendingDeliveryAttempt(ctx context.Context, arg RecordPendingDeliveryAttemptParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, recordPendingDeliveryAttempt,
		arg.NextAttemptAt,
		arg.LastError,
		arg.UpdatedAt,
		arg.DeliveryID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const requeueStaleAttemptedPendingDeliveries = `-- name: RequeueStaleAttemptedPendingDeliveries :execrows
UPDATE pending_deliveries
SET status = 'pending',
    next_attempt_at = ?,
    last_error = 'delivery attempt interrupted before completion',
    updated_at = ?
WHERE status = 'attempted'
  AND terminal_at IS NULL
  AND updated_at <= ?
`

type RequeueStaleAttemptedPendingDeliveriesParams struct {
	NextAttemptAt *string `json:"next_attempt_at"`
	UpdatedAt     string  `json:"updated_at"`
	UpdatedAt_2   string  `json:"updated_at_2"`
}

func (q *Queries) RequeueStaleAttemptedPendingDeliveries(ctx context.Context, arg RequeueStaleAttemptedPendingDeliveriesParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, requeueStaleAttemptedPendingDeliveries, arg.NextAttemptAt, arg.UpdatedAt, arg.UpdatedAt_2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const schedulePendingDeliveryRetry = `-- name: SchedulePendingDeliveryRetry :execrows
UPDATE pending_deliveries
SET status = 'pending',
    next_attempt_at = ?,
    last_error = ?,
    updated_at = ?
WHERE delivery_id = ? AND status = 'attempted'
`

type SchedulePendingDeliveryRetryParams struct {
	NextAttemptAt *string `json:"next_attempt_at"`
	LastError     string  `json:"last_error"`
	UpdatedAt     string  `json:"updated_at"`
	DeliveryID    string  `json:"delivery_id"`
}

func (q *Queries) SchedulePendingDeliveryRetry(ctx context.Context, arg SchedulePendingDeliveryRetryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, schedulePendingDeliveryRetry,
		arg.NextAttemptAt,
		arg.LastError,
		arg.UpdatedAt,
		arg.DeliveryID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
