// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pending_deliveries.sql

package dbsqlc

import (
	"context"
)

const claimDuePendingDeliveryAttempt = `-- name: ClaimDuePendingDeliveryAttempt :execrows
UPDATE pending_deliveries
SET status = 'attempted',
    attempts = attempts + 1,
    next_attempt_at = NULL,
    last_error = '',
    updated_at = ?
WHERE delivery_id = ?
  AND status = 'pending'
  AND next_attempt_at IS NOT NULL
  AND next_attempt_at <= ?
`

type ClaimDuePendingDeliveryAttemptParams struct {
	UpdatedAt     string  `json:"updated_at"`
	DeliveryID    string  `json:"delivery_id"`
	NextAttemptAt *string `json:"next_attempt_at"`
}

func (q *Queries) ClaimDuePendingDeliveryAttempt(ctx context.Context, arg ClaimDuePendingDeliveryAttemptParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimDuePendingDeliveryAttempt, arg.UpdatedAt, arg.DeliveryID, arg.NextAttemptAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const completePendingDelivery = `-- name: CompletePendingDelivery :execrows
UPDATE pending_deliveries
SET status = 'completed',
    updated_at = ?,
    terminal_at = ?
WHERE delivery_id = ? AND status IN ('pending', 'attempted')
`

type CompletePendingDeliveryParams struct {
	UpdatedAt  string  `json:"updated_at"`
	TerminalAt *string `json:"terminal_at"`
	DeliveryID string  `json:"delivery_id"`
}

func (q *Queries) CompletePendingDelivery(ctx context.Context, arg CompletePendingDeliveryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completePendingDelivery, arg.UpdatedAt, arg.TerminalAt, arg.DeliveryID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createPendingDelivery = `-- name: CreatePendingDelivery :exec
INSERT INTO pending_deliveries (
  delivery_id,
  workspace_id,
  subscription_id,
  target_type,
  target_id,
  delivery_policy_json,
  event_ids_json,
  status,
  attempts,
  next_attempt_at,
  deadline_at,
  last_error,
  created_at,
  updated_at,
  terminal_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreatePendingDeliveryParams struct {
	DeliveryID         string  `json:"delivery_id"`
	WorkspaceID        string  `json:"workspace_id"`
	SubscriptionID     string  `json:"subscription_id"`
	TargetType         string  `json:"target_type"`
	TargetID           string  `json:"target_id"`
	DeliveryPolicyJson string  `json:"delivery_policy_json"`
	EventIdsJson       string  `json:"event_ids_json"`
	Status             string  `json:"status"`
	Attempts           int64   `json:"attempts"`
	NextAttemptAt      *string `json:"next_attempt_at"`
	DeadlineAt         *string `json:"deadline_at"`
	LastError          string  `json:"last_error"`
	CreatedAt          string  `json:"created_at"`
	UpdatedAt          string  `json:"updated_at"`
	TerminalAt         *string `json:"terminal_at"`
}

func (q *Queries) CreatePendingDelivery(ctx context.Context, arg CreatePendingDeliveryParams) error {
	_, err := q.db.ExecContext(ctx, createPendingDelivery,
		arg.DeliveryID,
		arg.WorkspaceID,
		arg.SubscriptionID,
		arg.TargetType,
		arg.TargetID,
		arg.DeliveryPolicyJson,
		arg.EventIdsJson,
		arg.Status,
		arg.Attempts,
		arg.NextAttemptAt,
		arg.DeadlineAt,
		arg.LastError,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.TerminalAt,
	)
	return err
}

const failPendingDelivery = `-- name: FailPendingDelivery :execrows
UPDATE pending_deliveries
SET status = 'failed',
    last_error = ?,
    updated_at = ?,
    terminal_at = ?
WHERE delivery_id = ? AND status IN ('pending', 'attempted')
`

type FailPendingDeliveryParams struct {
	LastError  string  `json:"last_error"`
	UpdatedAt  string  `json:"updated_at"`
	TerminalAt *string `json:"terminal_at"`
	DeliveryID string  `json:"delivery_id"`
}

func (q *Queries) FailPendingDelivery(ctx context.Context, arg FailPendingDeliveryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, failPendingDelivery,
		arg.LastError,
		arg.UpdatedAt,
		arg.TerminalAt,
		arg.DeliveryID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getPendingDelivery = `-- name: GetPendingDelivery :one
SELECT delivery_id, workspace_id, subscription_id, target_type, target_id, delivery_policy_json, event_ids_json, status, attempts, next_attempt_at, deadline_at, last_error, created_at, updated_at, terminal_at
FROM pending_deliveries
WHERE delivery_id = ?
`

type GetPendingDeliveryParams struct {
	DeliveryID string `json:"delivery_id"`
}

func (q *Queries) GetPendingDelivery(ctx context.Context, arg GetPendingDeliveryParams) (PendingDelivery, error) {
	row := q.db.QueryRowContext(ctx, getPendingDelivery, arg.DeliveryID)
	var i PendingDelivery
	err := row.Scan(
		&i.DeliveryID,
		&i.WorkspaceID,
		&i.SubscriptionID,
		&i.TargetType,
		&i.TargetID,
		&i.DeliveryPolicyJson,
		&i.EventIdsJson,
		&i.Status,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.DeadlineAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TerminalAt,
	)
	return i, err
}

const listDuePendingDeliveries = `-- name: ListDuePendingDeliveries :many
SELECT delivery_id, workspace_id, subscription_id, target_type, target_id, delivery_policy_json, event_ids_json, status, attempts, next_attempt_at, deadline_at, last_error, created_at, updated_at, terminal_at
FROM pending_deliveries
WHERE status = 'pending' AND next_attempt_at IS NOT NULL AND next_attempt_at <= ?
ORDER BY next_attempt_at ASC, created_at ASC, delivery_id ASC
LIMIT ?
`

type ListDuePendingDeliveriesParams struct {
	NextAttemptAt *string `json:"next_attempt_at"`
	Limit         int64   `json:"limit"`
}

func (q *Queries) ListDuePendingDeliveries(ctx context.Context, arg ListDuePendingDeliveriesParams) ([]PendingDelivery, error) {
	rows, err := q.db.QueryContext(ctx, listDuePendingDeliveries, arg.NextAttemptAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PendingDelivery{}
	for rows.Next() {
		var i PendingDelivery
		if err := rows.Scan(
			&i.DeliveryID,
			&i.WorkspaceID,
			&i.SubscriptionID,
			&i.TargetType,
			&i.TargetID,
			&i.DeliveryPolicyJson,
			&i.EventIdsJson,
			&i.Status,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.DeadlineAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TerminalAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordPendingDeliveryAttempt = `-- name: RecordPendingDeliveryAttempt :execrows
UPDATE pending_deliveries
SET attempts = attempts + 1,
    next_attempt_at = ?,
    last_error = ?,
    updated_at = ?
WHERE delivery_id = ? AND status = 'pending'
`

type RecordPendingDeliveryAttemptParams struct {
	NextAttemptAt *string `json:"next_attempt_at"`
	LastError     string  `json:"last_error"`
	UpdatedAt     string  `json:"updated_at"`
	DeliveryID    string  `json:"delivery_id"`
}

func (q *Queries) RecordPendingDeliveryAttempt(ctx context.Context, arg RecordPendingDeliveryAttemptParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, recordPendingDeliveryAttempt,
		arg.NextAttemptAt,
		arg.LastError,
		arg.UpdatedAt,
		arg.DeliveryID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const schedulePendingDeliveryRetry = `-- name: SchedulePendingDeliveryRetry :execrows
UPDATE pending_deliveries
SET status = 'pending',
    next_attempt_at = ?,
    last_error = ?,
    updated_at = ?
WHERE delivery_id = ? AND status = 'attempted'
`

type SchedulePendingDeliveryRetryParams struct {
	NextAttemptAt *string `json:"next_attempt_at"`
	LastError     string  `json:"last_error"`
	UpdatedAt     string  `json:"updated_at"`
	DeliveryID    string  `json:"delivery_id"`
}

func (q *Queries) SchedulePendingDeliveryRetry(ctx context.Context, arg SchedulePendingDeliveryRetryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, schedulePendingDeliveryRetry,
		arg.NextAttemptAt,
		arg.LastError,
		arg.UpdatedAt,
		arg.DeliveryID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
