// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: secret_audit_events.sql

package dbsqlc

import (
	"context"
)

const createSecretAuditEvent = `-- name: CreateSecretAuditEvent :exec
INSERT INTO secret_audit_events (
  event_id,
  event_type,
  subject_type,
  subject_id,
  payload_json,
  created_at
) VALUES (?, ?, ?, ?, ?, ?)
`

type CreateSecretAuditEventParams struct {
	EventID     string `json:"event_id"`
	EventType   string `json:"event_type"`
	SubjectType string `json:"subject_type"`
	SubjectID   string `json:"subject_id"`
	PayloadJson string `json:"payload_json"`
	CreatedAt   string `json:"created_at"`
}

func (q *Queries) CreateSecretAuditEvent(ctx context.Context, arg CreateSecretAuditEventParams) error {
	_, err := q.db.ExecContext(ctx, createSecretAuditEvent,
		arg.EventID,
		arg.EventType,
		arg.SubjectType,
		arg.SubjectID,
		arg.PayloadJson,
		arg.CreatedAt,
	)
	return err
}

const listSecretAuditEvents = `-- name: ListSecretAuditEvents :many
SELECT event_id, event_type, subject_type, subject_id, payload_json, created_at
FROM secret_audit_events
ORDER BY created_at ASC, event_id ASC
LIMIT ?
`

type ListSecretAuditEventsParams struct {
	Limit int64 `json:"limit"`
}

func (q *Queries) ListSecretAuditEvents(ctx context.Context, arg ListSecretAuditEventsParams) ([]SecretAuditEvent, error) {
	rows, err := q.db.QueryContext(ctx, listSecretAuditEvents, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SecretAuditEvent{}
	for rows.Next() {
		var i SecretAuditEvent
		if err := rows.Scan(
			&i.EventID,
			&i.EventType,
			&i.SubjectType,
			&i.SubjectID,
			&i.PayloadJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
