// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: timeline_items.sql

package dbsqlc

import (
	"context"
)

const createTimelineItem = `-- name: CreateTimelineItem :execrows
INSERT INTO timeline_items (
  workspace_id,
  timeline_item_id,
  workspace_event_id,
  sequence,
  run_id,
  session_id,
  source_kind,
  source_id,
  kind,
  status,
  text,
  metadata_json,
  created_at,
  updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(workspace_id, timeline_item_id) DO NOTHING
`

type CreateTimelineItemParams struct {
	WorkspaceID      string `json:"workspace_id"`
	TimelineItemID   string `json:"timeline_item_id"`
	WorkspaceEventID string `json:"workspace_event_id"`
	Sequence         int64  `json:"sequence"`
	RunID            string `json:"run_id"`
	SessionID        string `json:"session_id"`
	SourceKind       string `json:"source_kind"`
	SourceID         string `json:"source_id"`
	Kind             string `json:"kind"`
	Status           string `json:"status"`
	Text             string `json:"text"`
	MetadataJson     string `json:"metadata_json"`
	CreatedAt        string `json:"created_at"`
	UpdatedAt        string `json:"updated_at"`
}

func (q *Queries) CreateTimelineItem(ctx context.Context, arg CreateTimelineItemParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createTimelineItem,
		arg.WorkspaceID,
		arg.TimelineItemID,
		arg.WorkspaceEventID,
		arg.Sequence,
		arg.RunID,
		arg.SessionID,
		arg.SourceKind,
		arg.SourceID,
		arg.Kind,
		arg.Status,
		arg.Text,
		arg.MetadataJson,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTimelineItemsByWorkspace = `-- name: DeleteTimelineItemsByWorkspace :execrows
DELETE FROM timeline_items
WHERE workspace_id = ?
`

type DeleteTimelineItemsByWorkspaceParams struct {
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) DeleteTimelineItemsByWorkspace(ctx context.Context, arg DeleteTimelineItemsByWorkspaceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTimelineItemsByWorkspace, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getTimelineItem = `-- name: GetTimelineItem :one
SELECT workspace_id, timeline_item_id, workspace_event_id, sequence, run_id, session_id, source_kind, source_id, kind, status, text, metadata_json, created_at, updated_at
FROM timeline_items
WHERE workspace_id = ? AND timeline_item_id = ?
`

type GetTimelineItemParams struct {
	WorkspaceID    string `json:"workspace_id"`
	TimelineItemID string `json:"timeline_item_id"`
}

func (q *Queries) GetTimelineItem(ctx context.Context, arg GetTimelineItemParams) (TimelineItem, error) {
	row := q.db.QueryRowContext(ctx, getTimelineItem, arg.WorkspaceID, arg.TimelineItemID)
	var i TimelineItem
	err := row.Scan(
		&i.WorkspaceID,
		&i.TimelineItemID,
		&i.WorkspaceEventID,
		&i.Sequence,
		&i.RunID,
		&i.SessionID,
		&i.SourceKind,
		&i.SourceID,
		&i.Kind,
		&i.Status,
		&i.Text,
		&i.MetadataJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTimelineItemsByWorkspace = `-- name: ListTimelineItemsByWorkspace :many
SELECT workspace_id, timeline_item_id, workspace_event_id, sequence, run_id, session_id, source_kind, source_id, kind, status, text, metadata_json, created_at, updated_at
FROM timeline_items
WHERE workspace_id = ?
ORDER BY sequence ASC, timeline_item_id ASC
`

type ListTimelineItemsByWorkspaceParams struct {
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) ListTimelineItemsByWorkspace(ctx context.Context, arg ListTimelineItemsByWorkspaceParams) ([]TimelineItem, error) {
	rows, err := q.db.QueryContext(ctx, listTimelineItemsByWorkspace, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TimelineItem{}
	for rows.Next() {
		var i TimelineItem
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.TimelineItemID,
			&i.WorkspaceEventID,
			&i.Sequence,
			&i.RunID,
			&i.SessionID,
			&i.SourceKind,
			&i.SourceID,
			&i.Kind,
			&i.Status,
			&i.Text,
			&i.MetadataJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextTimelineItemSequence = `-- name: NextTimelineItemSequence :one
SELECT CAST(COALESCE(MAX(sequence), 0) + 1 AS INTEGER) AS next_sequence
FROM timeline_items
WHERE workspace_id = ?
`

type NextTimelineItemSequenceParams struct {
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) NextTimelineItemSequence(ctx context.Context, arg NextTimelineItemSequenceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextTimelineItemSequence, arg.WorkspaceID)
	var next_sequence int64
	err := row.Scan(&next_sequence)
	return next_sequence, err
}

const updateTimelineItem = `-- name: UpdateTimelineItem :execrows
UPDATE timeline_items
SET workspace_event_id = ?,
    run_id = ?,
    session_id = ?,
    source_kind = ?,
    source_id = ?,
    kind = ?,
    status = ?,
    text = ?,
    metadata_json = ?,
    created_at = ?,
    updated_at = ?
WHERE workspace_id = ? AND timeline_item_id = ?
`

type UpdateTimelineItemParams struct {
	WorkspaceEventID string `json:"workspace_event_id"`
	RunID            string `json:"run_id"`
	SessionID        string `json:"session_id"`
	SourceKind       string `json:"source_kind"`
	SourceID         string `json:"source_id"`
	Kind             string `json:"kind"`
	Status           string `json:"status"`
	Text             string `json:"text"`
	MetadataJson     string `json:"metadata_json"`
	CreatedAt        string `json:"created_at"`
	UpdatedAt        string `json:"updated_at"`
	WorkspaceID      string `json:"workspace_id"`
	TimelineItemID   string `json:"timeline_item_id"`
}

func (q *Queries) UpdateTimelineItem(ctx context.Context, arg UpdateTimelineItemParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTimelineItem,
		arg.WorkspaceEventID,
		arg.RunID,
		arg.SessionID,
		arg.SourceKind,
		arg.SourceID,
		arg.Kind,
		arg.Status,
		arg.Text,
		arg.MetadataJson,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.WorkspaceID,
		arg.TimelineItemID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
