// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: workspace_command_definitions.sql

package dbsqlc

import (
	"context"
)

const createWorkspaceCommandDefinition = `-- name: CreateWorkspaceCommandDefinition :exec
INSERT INTO workspace_command_definitions (
  command_id, workspace_id, name, command, args, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateWorkspaceCommandDefinitionParams struct {
	CommandID   string `json:"command_id"`
	WorkspaceID string `json:"workspace_id"`
	Name        string `json:"name"`
	Command     string `json:"command"`
	Args        string `json:"args"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

func (q *Queries) CreateWorkspaceCommandDefinition(ctx context.Context, arg CreateWorkspaceCommandDefinitionParams) error {
	_, err := q.db.ExecContext(ctx, createWorkspaceCommandDefinition,
		arg.CommandID,
		arg.WorkspaceID,
		arg.Name,
		arg.Command,
		arg.Args,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteWorkspaceCommandDefinitionByID = `-- name: DeleteWorkspaceCommandDefinitionByID :execrows
DELETE FROM workspace_command_definitions
WHERE workspace_id = ? AND command_id = ?
`

type DeleteWorkspaceCommandDefinitionByIDParams struct {
	WorkspaceID string `json:"workspace_id"`
	CommandID   string `json:"command_id"`
}

func (q *Queries) DeleteWorkspaceCommandDefinitionByID(ctx context.Context, arg DeleteWorkspaceCommandDefinitionByIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteWorkspaceCommandDefinitionByID, arg.WorkspaceID, arg.CommandID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getWorkspaceCommandDefinitionByID = `-- name: GetWorkspaceCommandDefinitionByID :one
SELECT command_id, workspace_id, name, command, args, created_at, updated_at
FROM workspace_command_definitions
WHERE workspace_id = ? AND command_id = ?
`

type GetWorkspaceCommandDefinitionByIDParams struct {
	WorkspaceID string `json:"workspace_id"`
	CommandID   string `json:"command_id"`
}

func (q *Queries) GetWorkspaceCommandDefinitionByID(ctx context.Context, arg GetWorkspaceCommandDefinitionByIDParams) (WorkspaceCommandDefinition, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceCommandDefinitionByID, arg.WorkspaceID, arg.CommandID)
	var i WorkspaceCommandDefinition
	err := row.Scan(
		&i.CommandID,
		&i.WorkspaceID,
		&i.Name,
		&i.Command,
		&i.Args,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceCommandDefinitionByName = `-- name: GetWorkspaceCommandDefinitionByName :one
SELECT command_id, workspace_id, name, command, args, created_at, updated_at
FROM workspace_command_definitions
WHERE workspace_id = ? AND name = ?
`

type GetWorkspaceCommandDefinitionByNameParams struct {
	WorkspaceID string `json:"workspace_id"`
	Name        string `json:"name"`
}

func (q *Queries) GetWorkspaceCommandDefinitionByName(ctx context.Context, arg GetWorkspaceCommandDefinitionByNameParams) (WorkspaceCommandDefinition, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceCommandDefinitionByName, arg.WorkspaceID, arg.Name)
	var i WorkspaceCommandDefinition
	err := row.Scan(
		&i.CommandID,
		&i.WorkspaceID,
		&i.Name,
		&i.Command,
		&i.Args,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkspaceCommandDefinitionsByWorkspace = `-- name: ListWorkspaceCommandDefinitionsByWorkspace :many
SELECT command_id, workspace_id, name, command, args, created_at, updated_at
FROM workspace_command_definitions
WHERE workspace_id = ?
ORDER BY created_at DESC, command_id ASC
`

type ListWorkspaceCommandDefinitionsByWorkspaceParams struct {
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) ListWorkspaceCommandDefinitionsByWorkspace(ctx context.Context, arg ListWorkspaceCommandDefinitionsByWorkspaceParams) ([]WorkspaceCommandDefinition, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaceCommandDefinitionsByWorkspace, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceCommandDefinition{}
	for rows.Next() {
		var i WorkspaceCommandDefinition
		if err := rows.Scan(
			&i.CommandID,
			&i.WorkspaceID,
			&i.Name,
			&i.Command,
			&i.Args,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
