// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspace_events.sql

package dbsqlc

import (
	"context"
)

const cancelEventSubscription = `-- name: CancelEventSubscription :execrows
UPDATE event_subscriptions
SET status = 'canceled',
    updated_at = ?
WHERE subscription_id = ? AND status != 'canceled'
`

type CancelEventSubscriptionParams struct {
	UpdatedAt      string `json:"updated_at"`
	SubscriptionID string `json:"subscription_id"`
}

func (q *Queries) CancelEventSubscription(ctx context.Context, arg CancelEventSubscriptionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, cancelEventSubscription, arg.UpdatedAt, arg.SubscriptionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createEventSubscription = `-- name: CreateEventSubscription :exec
INSERT INTO event_subscriptions (
  subscription_id,
  workspace_id,
  owner_session_id,
  name,
  filter_json,
  delivery_target_type,
  delivery_target_id,
  delivery_policy_json,
  cursor_sequence,
  ack_sequence,
  status,
  completion_condition_json,
  timeout_at,
  created_at,
  updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateEventSubscriptionParams struct {
	SubscriptionID          string  `json:"subscription_id"`
	WorkspaceID             string  `json:"workspace_id"`
	OwnerSessionID          string  `json:"owner_session_id"`
	Name                    string  `json:"name"`
	FilterJson              string  `json:"filter_json"`
	DeliveryTargetType      string  `json:"delivery_target_type"`
	DeliveryTargetID        string  `json:"delivery_target_id"`
	DeliveryPolicyJson      string  `json:"delivery_policy_json"`
	CursorSequence          int64   `json:"cursor_sequence"`
	AckSequence             int64   `json:"ack_sequence"`
	Status                  string  `json:"status"`
	CompletionConditionJson string  `json:"completion_condition_json"`
	TimeoutAt               *string `json:"timeout_at"`
	CreatedAt               string  `json:"created_at"`
	UpdatedAt               string  `json:"updated_at"`
}

func (q *Queries) CreateEventSubscription(ctx context.Context, arg CreateEventSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, createEventSubscription,
		arg.SubscriptionID,
		arg.WorkspaceID,
		arg.OwnerSessionID,
		arg.Name,
		arg.FilterJson,
		arg.DeliveryTargetType,
		arg.DeliveryTargetID,
		arg.DeliveryPolicyJson,
		arg.CursorSequence,
		arg.AckSequence,
		arg.Status,
		arg.CompletionConditionJson,
		arg.TimeoutAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createWorkspaceEvent = `-- name: CreateWorkspaceEvent :exec
INSERT INTO workspace_events (
  event_id,
  workspace_id,
  sequence,
  event_type,
  subject_type,
  subject_id,
  producer_type,
  producer_id,
  correlation_id,
  causation_id,
  payload_json,
  payload_ref_json,
  attention_required,
  created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateWorkspaceEventParams struct {
	EventID           string `json:"event_id"`
	WorkspaceID       string `json:"workspace_id"`
	Sequence          int64  `json:"sequence"`
	EventType         string `json:"event_type"`
	SubjectType       string `json:"subject_type"`
	SubjectID         string `json:"subject_id"`
	ProducerType      string `json:"producer_type"`
	ProducerID        string `json:"producer_id"`
	CorrelationID     string `json:"correlation_id"`
	CausationID       string `json:"causation_id"`
	PayloadJson       string `json:"payload_json"`
	PayloadRefJson    string `json:"payload_ref_json"`
	AttentionRequired int64  `json:"attention_required"`
	CreatedAt         string `json:"created_at"`
}

func (q *Queries) CreateWorkspaceEvent(ctx context.Context, arg CreateWorkspaceEventParams) error {
	_, err := q.db.ExecContext(ctx, createWorkspaceEvent,
		arg.EventID,
		arg.WorkspaceID,
		arg.Sequence,
		arg.EventType,
		arg.SubjectType,
		arg.SubjectID,
		arg.ProducerType,
		arg.ProducerID,
		arg.CorrelationID,
		arg.CausationID,
		arg.PayloadJson,
		arg.PayloadRefJson,
		arg.AttentionRequired,
		arg.CreatedAt,
	)
	return err
}

const getEventSubscription = `-- name: GetEventSubscription :one
SELECT subscription_id, workspace_id, owner_session_id, name, filter_json, delivery_target_type, delivery_target_id, delivery_policy_json, cursor_sequence, ack_sequence, status, completion_condition_json, timeout_at, created_at, updated_at
FROM event_subscriptions
WHERE subscription_id = ?
`

type GetEventSubscriptionParams struct {
	SubscriptionID string `json:"subscription_id"`
}

func (q *Queries) GetEventSubscription(ctx context.Context, arg GetEventSubscriptionParams) (EventSubscription, error) {
	row := q.db.QueryRowContext(ctx, getEventSubscription, arg.SubscriptionID)
	var i EventSubscription
	err := row.Scan(
		&i.SubscriptionID,
		&i.WorkspaceID,
		&i.OwnerSessionID,
		&i.Name,
		&i.FilterJson,
		&i.DeliveryTargetType,
		&i.DeliveryTargetID,
		&i.DeliveryPolicyJson,
		&i.CursorSequence,
		&i.AckSequence,
		&i.Status,
		&i.CompletionConditionJson,
		&i.TimeoutAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceEvent = `-- name: GetWorkspaceEvent :one
SELECT event_id, workspace_id, sequence, event_type, subject_type, subject_id, producer_type, producer_id, correlation_id, causation_id, payload_json, payload_ref_json, attention_required, created_at
FROM workspace_events
WHERE event_id = ?
`

type GetWorkspaceEventParams struct {
	EventID string `json:"event_id"`
}

func (q *Queries) GetWorkspaceEvent(ctx context.Context, arg GetWorkspaceEventParams) (WorkspaceEvent, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceEvent, arg.EventID)
	var i WorkspaceEvent
	err := row.Scan(
		&i.EventID,
		&i.WorkspaceID,
		&i.Sequence,
		&i.EventType,
		&i.SubjectType,
		&i.SubjectID,
		&i.ProducerType,
		&i.ProducerID,
		&i.CorrelationID,
		&i.CausationID,
		&i.PayloadJson,
		&i.PayloadRefJson,
		&i.AttentionRequired,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveEventSubscriptionsByWorkspace = `-- name: ListActiveEventSubscriptionsByWorkspace :many
SELECT subscription_id, workspace_id, owner_session_id, name, filter_json, delivery_target_type, delivery_target_id, delivery_policy_json, cursor_sequence, ack_sequence, status, completion_condition_json, timeout_at, created_at, updated_at
FROM event_subscriptions
WHERE workspace_id = ? AND status = 'active'
ORDER BY created_at ASC, subscription_id ASC
`

type ListActiveEventSubscriptionsByWorkspaceParams struct {
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) ListActiveEventSubscriptionsByWorkspace(ctx context.Context, arg ListActiveEventSubscriptionsByWorkspaceParams) ([]EventSubscription, error) {
	rows, err := q.db.QueryContext(ctx, listActiveEventSubscriptionsByWorkspace, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventSubscription{}
	for rows.Next() {
		var i EventSubscription
		if err := rows.Scan(
			&i.SubscriptionID,
			&i.WorkspaceID,
			&i.OwnerSessionID,
			&i.Name,
			&i.FilterJson,
			&i.DeliveryTargetType,
			&i.DeliveryTargetID,
			&i.DeliveryPolicyJson,
			&i.CursorSequence,
			&i.AckSequence,
			&i.Status,
			&i.CompletionConditionJson,
			&i.TimeoutAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceEventsAfterSequence = `-- name: ListWorkspaceEventsAfterSequence :many
SELECT event_id, workspace_id, sequence, event_type, subject_type, subject_id, producer_type, producer_id, correlation_id, causation_id, payload_json, payload_ref_json, attention_required, created_at
FROM workspace_events
WHERE workspace_id = ? AND sequence > ?
ORDER BY sequence ASC
LIMIT ?
`

type ListWorkspaceEventsAfterSequenceParams struct {
	WorkspaceID string `json:"workspace_id"`
	Sequence    int64  `json:"sequence"`
	Limit       int64  `json:"limit"`
}

func (q *Queries) ListWorkspaceEventsAfterSequence(ctx context.Context, arg ListWorkspaceEventsAfterSequenceParams) ([]WorkspaceEvent, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaceEventsAfterSequence, arg.WorkspaceID, arg.Sequence, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceEvent{}
	for rows.Next() {
		var i WorkspaceEvent
		if err := rows.Scan(
			&i.EventID,
			&i.WorkspaceID,
			&i.Sequence,
			&i.EventType,
			&i.SubjectType,
			&i.SubjectID,
			&i.ProducerType,
			&i.ProducerID,
			&i.CorrelationID,
			&i.CausationID,
			&i.PayloadJson,
			&i.PayloadRefJson,
			&i.AttentionRequired,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextWorkspaceEventSequence = `-- name: NextWorkspaceEventSequence :one
SELECT COALESCE(MAX(sequence), 0) + 1
FROM workspace_events
WHERE workspace_id = ?
`

type NextWorkspaceEventSequenceParams struct {
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) NextWorkspaceEventSequence(ctx context.Context, arg NextWorkspaceEventSequenceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextWorkspaceEventSequence, arg.WorkspaceID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateEventSubscriptionCursor = `-- name: UpdateEventSubscriptionCursor :execrows
UPDATE event_subscriptions
SET cursor_sequence = CASE WHEN cursor_sequence < ? THEN ? ELSE cursor_sequence END,
    ack_sequence = CASE WHEN ack_sequence < ? THEN ? ELSE ack_sequence END,
    updated_at = ?
WHERE subscription_id = ?
`

type UpdateEventSubscriptionCursorParams struct {
	CursorSequence   int64  `json:"cursor_sequence"`
	CursorSequence_2 int64  `json:"cursor_sequence_2"`
	AckSequence      int64  `json:"ack_sequence"`
	AckSequence_2    int64  `json:"ack_sequence_2"`
	UpdatedAt        string `json:"updated_at"`
	SubscriptionID   string `json:"subscription_id"`
}

func (q *Queries) UpdateEventSubscriptionCursor(ctx context.Context, arg UpdateEventSubscriptionCursorParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateEventSubscriptionCursor,
		arg.CursorSequence,
		arg.CursorSequence_2,
		arg.AckSequence,
		arg.AckSequence_2,
		arg.UpdatedAt,
		arg.SubscriptionID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
