// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspace_timers.sql

package dbsqlc

import (
	"context"
)

const cancelWorkspaceTimer = `-- name: CancelWorkspaceTimer :execrows
UPDATE workspace_timers
SET status = 'canceled',
    updated_at = ?
WHERE timer_id = ? AND status = 'scheduled'
`

type CancelWorkspaceTimerParams struct {
	UpdatedAt string `json:"updated_at"`
	TimerID   string `json:"timer_id"`
}

func (q *Queries) CancelWorkspaceTimer(ctx context.Context, arg CancelWorkspaceTimerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, cancelWorkspaceTimer, arg.UpdatedAt, arg.TimerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const cancelWorkspaceTimersByTargetSubscription = `-- name: CancelWorkspaceTimersByTargetSubscription :execrows
UPDATE workspace_timers
SET status = 'canceled',
    updated_at = ?
WHERE target_subscription_id = ? AND status = 'scheduled'
`

type CancelWorkspaceTimersByTargetSubscriptionParams struct {
	UpdatedAt            string  `json:"updated_at"`
	TargetSubscriptionID *string `json:"target_subscription_id"`
}

func (q *Queries) CancelWorkspaceTimersByTargetSubscription(ctx context.Context, arg CancelWorkspaceTimersByTargetSubscriptionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, cancelWorkspaceTimersByTargetSubscription, arg.UpdatedAt, arg.TargetSubscriptionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createWorkspaceTimer = `-- name: CreateWorkspaceTimer :exec
INSERT INTO workspace_timers (
  timer_id,
  workspace_id,
  owner_session_id,
  target_subscription_id,
  subject_type,
  subject_id,
  purpose,
  status,
  fire_at,
  payload_json,
  fired_event_id,
  created_at,
  updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateWorkspaceTimerParams struct {
	TimerID              string  `json:"timer_id"`
	WorkspaceID          string  `json:"workspace_id"`
	OwnerSessionID       string  `json:"owner_session_id"`
	TargetSubscriptionID *string `json:"target_subscription_id"`
	SubjectType          string  `json:"subject_type"`
	SubjectID            string  `json:"subject_id"`
	Purpose              string  `json:"purpose"`
	Status               string  `json:"status"`
	FireAt               string  `json:"fire_at"`
	PayloadJson          string  `json:"payload_json"`
	FiredEventID         string  `json:"fired_event_id"`
	CreatedAt            string  `json:"created_at"`
	UpdatedAt            string  `json:"updated_at"`
}

func (q *Queries) CreateWorkspaceTimer(ctx context.Context, arg CreateWorkspaceTimerParams) error {
	_, err := q.db.ExecContext(ctx, createWorkspaceTimer,
		arg.TimerID,
		arg.WorkspaceID,
		arg.OwnerSessionID,
		arg.TargetSubscriptionID,
		arg.SubjectType,
		arg.SubjectID,
		arg.Purpose,
		arg.Status,
		arg.FireAt,
		arg.PayloadJson,
		arg.FiredEventID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getWorkspaceTimer = `-- name: GetWorkspaceTimer :one
SELECT timer_id, workspace_id, owner_session_id, target_subscription_id, subject_type, subject_id, purpose, status, fire_at, payload_json, fired_event_id, created_at, updated_at
FROM workspace_timers
WHERE timer_id = ?
`

type GetWorkspaceTimerParams struct {
	TimerID string `json:"timer_id"`
}

func (q *Queries) GetWorkspaceTimer(ctx context.Context, arg GetWorkspaceTimerParams) (WorkspaceTimer, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceTimer, arg.TimerID)
	var i WorkspaceTimer
	err := row.Scan(
		&i.TimerID,
		&i.WorkspaceID,
		&i.OwnerSessionID,
		&i.TargetSubscriptionID,
		&i.SubjectType,
		&i.SubjectID,
		&i.Purpose,
		&i.Status,
		&i.FireAt,
		&i.PayloadJson,
		&i.FiredEventID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDueWorkspaceTimers = `-- name: ListDueWorkspaceTimers :many
SELECT timer_id, workspace_id, owner_session_id, target_subscription_id, subject_type, subject_id, purpose, status, fire_at, payload_json, fired_event_id, created_at, updated_at
FROM workspace_timers
WHERE status = 'scheduled' AND fire_at <= ?
ORDER BY fire_at ASC, timer_id ASC
LIMIT ?
`

type ListDueWorkspaceTimersParams struct {
	FireAt string `json:"fire_at"`
	Limit  int64  `json:"limit"`
}

func (q *Queries) ListDueWorkspaceTimers(ctx context.Context, arg ListDueWorkspaceTimersParams) ([]WorkspaceTimer, error) {
	rows, err := q.db.QueryContext(ctx, listDueWorkspaceTimers, arg.FireAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceTimer{}
	for rows.Next() {
		var i WorkspaceTimer
		if err := rows.Scan(
			&i.TimerID,
			&i.WorkspaceID,
			&i.OwnerSessionID,
			&i.TargetSubscriptionID,
			&i.SubjectType,
			&i.SubjectID,
			&i.Purpose,
			&i.Status,
			&i.FireAt,
			&i.PayloadJson,
			&i.FiredEventID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWorkspaceTimerFired = `-- name: MarkWorkspaceTimerFired :execrows
UPDATE workspace_timers
SET status = 'fired',
    fired_event_id = ?,
    updated_at = ?
WHERE timer_id = ? AND status = 'scheduled'
`

type MarkWorkspaceTimerFiredParams struct {
	FiredEventID string `json:"fired_event_id"`
	UpdatedAt    string `json:"updated_at"`
	TimerID      string `json:"timer_id"`
}

func (q *Queries) MarkWorkspaceTimerFired(ctx context.Context, arg MarkWorkspaceTimerFiredParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markWorkspaceTimerFired, arg.FiredEventID, arg.UpdatedAt, arg.TimerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const nextScheduledWorkspaceTimerFireAt = `-- name: NextScheduledWorkspaceTimerFireAt :one
SELECT fire_at
FROM workspace_timers
WHERE status = 'scheduled'
ORDER BY fire_at ASC, timer_id ASC
LIMIT 1
`

func (q *Queries) NextScheduledWorkspaceTimerFireAt(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, nextScheduledWorkspaceTimerFireAt)
	var fire_at string
	err := row.Scan(&fire_at)
	return fire_at, err
}
