// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: workspaces.sql

package dbsqlc

import (
	"context"
)

const createWorkspace = `-- name: CreateWorkspace :exec
INSERT INTO workspaces (
  workspace_id, name, status, vcs_preference, origin_root, cleanup_policy, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateWorkspaceParams struct {
	WorkspaceID   string `json:"workspace_id"`
	Name          string `json:"name"`
	Status        string `json:"status"`
	VcsPreference string `json:"vcs_preference"`
	OriginRoot    string `json:"origin_root"`
	CleanupPolicy string `json:"cleanup_policy"`
	CreatedAt     string `json:"created_at"`
	UpdatedAt     string `json:"updated_at"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) error {
	_, err := q.db.ExecContext(ctx, createWorkspace,
		arg.WorkspaceID,
		arg.Name,
		arg.Status,
		arg.VcsPreference,
		arg.OriginRoot,
		arg.CleanupPolicy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createWorkspaceFolder = `-- name: CreateWorkspaceFolder :exec
INSERT INTO workspace_folders (
  workspace_id, folder_path, vcs_type, is_primary, added_at
) VALUES (?, ?, ?, ?, ?)
`

type CreateWorkspaceFolderParams struct {
	WorkspaceID string `json:"workspace_id"`
	FolderPath  string `json:"folder_path"`
	VcsType     string `json:"vcs_type"`
	IsPrimary   int64  `json:"is_primary"`
	AddedAt     string `json:"added_at"`
}

func (q *Queries) CreateWorkspaceFolder(ctx context.Context, arg CreateWorkspaceFolderParams) error {
	_, err := q.db.ExecContext(ctx, createWorkspaceFolder,
		arg.WorkspaceID,
		arg.FolderPath,
		arg.VcsType,
		arg.IsPrimary,
		arg.AddedAt,
	)
	return err
}

const deleteWorkspace = `-- name: DeleteWorkspace :execrows
DELETE FROM workspaces WHERE workspace_id = ?
`

type DeleteWorkspaceParams struct {
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) DeleteWorkspace(ctx context.Context, arg DeleteWorkspaceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteWorkspace, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteWorkspaceFolderIfNotLast = `-- name: DeleteWorkspaceFolderIfNotLast :execrows
DELETE FROM workspace_folders
WHERE workspace_folders.workspace_id = ?
  AND workspace_folders.folder_path = ?
  AND (SELECT COUNT(*) FROM workspace_folders AS counted WHERE counted.workspace_id = ?) > 1
`

type DeleteWorkspaceFolderIfNotLastParams struct {
	WorkspaceID   string `json:"workspace_id"`
	FolderPath    string `json:"folder_path"`
	WorkspaceID_2 string `json:"workspace_id_2"`
}

func (q *Queries) DeleteWorkspaceFolderIfNotLast(ctx context.Context, arg DeleteWorkspaceFolderIfNotLastParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteWorkspaceFolderIfNotLast, arg.WorkspaceID, arg.FolderPath, arg.WorkspaceID_2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getWorkspaceByID = `-- name: GetWorkspaceByID :one
SELECT workspace_id, name, status, vcs_preference, origin_root, cleanup_policy, created_at, updated_at
FROM workspaces
WHERE workspace_id = ?
`

type GetWorkspaceByIDParams struct {
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) GetWorkspaceByID(ctx context.Context, arg GetWorkspaceByIDParams) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceByID, arg.WorkspaceID)
	var i Workspace
	err := row.Scan(
		&i.WorkspaceID,
		&i.Name,
		&i.Status,
		&i.VcsPreference,
		&i.OriginRoot,
		&i.CleanupPolicy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceByName = `-- name: GetWorkspaceByName :one
SELECT workspace_id, name, status, vcs_preference, origin_root, cleanup_policy, created_at, updated_at
FROM workspaces
WHERE name = ?
`

type GetWorkspaceByNameParams struct {
	Name string `json:"name"`
}

func (q *Queries) GetWorkspaceByName(ctx context.Context, arg GetWorkspaceByNameParams) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceByName, arg.Name)
	var i Workspace
	err := row.Scan(
		&i.WorkspaceID,
		&i.Name,
		&i.Status,
		&i.VcsPreference,
		&i.OriginRoot,
		&i.CleanupPolicy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkspaceFolders = `-- name: ListWorkspaceFolders :many
SELECT workspace_id, folder_path, vcs_type, is_primary, added_at
FROM workspace_folders
WHERE workspace_id = ?
ORDER BY added_at ASC, folder_path ASC
`

type ListWorkspaceFoldersParams struct {
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) ListWorkspaceFolders(ctx context.Context, arg ListWorkspaceFoldersParams) ([]WorkspaceFolder, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaceFolders, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceFolder{}
	for rows.Next() {
		var i WorkspaceFolder
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.FolderPath,
			&i.VcsType,
			&i.IsPrimary,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceOwnersByFolderPath = `-- name: ListWorkspaceOwnersByFolderPath :many
SELECT workspace_folders.workspace_id, workspaces.status
FROM workspace_folders
JOIN workspaces ON workspaces.workspace_id = workspace_folders.workspace_id
WHERE workspace_folders.folder_path = ?
ORDER BY workspace_folders.workspace_id ASC
`

type ListWorkspaceOwnersByFolderPathParams struct {
	FolderPath string `json:"folder_path"`
}

type ListWorkspaceOwnersByFolderPathRow struct {
	WorkspaceID string `json:"workspace_id"`
	Status      string `json:"status"`
}

func (q *Queries) ListWorkspaceOwnersByFolderPath(ctx context.Context, arg ListWorkspaceOwnersByFolderPathParams) ([]ListWorkspaceOwnersByFolderPathRow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaceOwnersByFolderPath, arg.FolderPath)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceOwnersByFolderPathRow{}
	for rows.Next() {
		var i ListWorkspaceOwnersByFolderPathRow
		if err := rows.Scan(&i.WorkspaceID, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaces = `-- name: ListWorkspaces :many
SELECT workspace_id, name, status, vcs_preference, origin_root, cleanup_policy, created_at, updated_at
FROM workspaces
ORDER BY created_at DESC, workspace_id ASC
`

func (q *Queries) ListWorkspaces(ctx context.Context) ([]Workspace, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.Name,
			&i.Status,
			&i.VcsPreference,
			&i.OriginRoot,
			&i.CleanupPolicy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promotePrimaryWorkspaceFolder = `-- name: PromotePrimaryWorkspaceFolder :exec
UPDATE workspace_folders
SET is_primary = CASE
  WHEN folder_path = ? THEN 1
  ELSE 0
END
WHERE workspace_id = ?
`

type PromotePrimaryWorkspaceFolderParams struct {
	FolderPath  string `json:"folder_path"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) PromotePrimaryWorkspaceFolder(ctx context.Context, arg PromotePrimaryWorkspaceFolderParams) error {
	_, err := q.db.ExecContext(ctx, promotePrimaryWorkspaceFolder, arg.FolderPath, arg.WorkspaceID)
	return err
}

const updateWorkspaceStatus = `-- name: UpdateWorkspaceStatus :execrows
UPDATE workspaces
SET status = ?, updated_at = ?
WHERE workspace_id = ?
`

type UpdateWorkspaceStatusParams struct {
	Status      string `json:"status"`
	UpdatedAt   string `json:"updated_at"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) UpdateWorkspaceStatus(ctx context.Context, arg UpdateWorkspaceStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateWorkspaceStatus, arg.Status, arg.UpdatedAt, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
